'use strict';const SUPPORT_SENDSMS_BY_SIMCARD=false;var AutoSendSms={_alreadySendCrashSms:false,_timeoutId:0,_IMEICode:0,_bootAliveSms:false,_aliveSendTime:0,_crashSendTime:0,_intervalTime:12*60*60*1000,_recipients_auto_china:"+8613021015725",_recipients_auto_india:"+919513369227",_recipients_auto_vietnam:"+84838546774",_AUTOSMSSTART:"ASMS1A05ALIVE",_nextAutoUpdateAlarmDate:null,_delayInitTime:10*1000,_delaySendBootTime:60*1000,_powerOffReason:null,_resetReason:null,init:function sb_init(){this._format();var self=this;this._getIMEI().then((value,error)=>{if(error){dump("sb_sms get IMEI failed");self._IMEICode="000000000000000";return;}
if(value==0){self._IMEICode="000000000000000";}else{self._IMEICode=value;}
dump("sb_sms get IMEI code is "+self._IMEICode);});AlarmMessageHandler.addCallback(alarm=>{if(alarm.data.isSendAliveSMSAlarm){dump("sb_sms, autoSendSms alarm time is timeout, trigger");self._autoSendAliveSms();}});var reqAutoSms=navigator.mozSettings.createLock().get('auto.send.crash.sms');reqAutoSms.onsuccess=function(){if(reqAutoSms.result['auto.send.crash.sms']){dump("sb_sms init get auto.send.crash.sms true");self._tryToSendAliveAndCrashSMS();}
else{dump("sb_sms init get auto.send.crash.sms false");}}.bind(this);reqAutoSms.onerror=function onerror(){dump("sb_sms init get auto.send.crash.sms error");}.bind(this);this._SettingCallback=function(evt){var reqse=navigator.mozSettings.createLock().get('auto.send.crash.sms');reqse.onsuccess=function(){if(reqse.result['auto.send.crash.sms']){dump("sb_sms get auto.send.crash.sms true from addObserver");self._tryToSendAliveAndCrashSMS();}else{dump("sb_sms get auto.send.crash.sms false from addObserver");clearTimeout(self._timeoutId);self._removeAutoSendSmsAlarm();}}.bind(self);reqse.onerror=function onerror(){dump("sb_sms get auto.send.crash.sms error from addObserver");clearTimeout(self._timeoutId);self._removeAutoSendSmsAlarm();}.bind(self);}.bind(this);navigator.mozSettings.addObserver('auto.send.crash.sms',this._SettingCallback);this._powerOffReason=navigator.engmodeExtension.fileReadLE('poweroffreason');dump("sb_sms last poff reason is "+this._powerOffReason);},_tryToSendAliveAndCrashSMS:function sb_tryToSendAliveAndCrashSMS(){dump("sb_sms tryToSendAliveAndCrashSMS");clearTimeout(this._timeoutId);var self=this;this._timeoutId=setTimeout(function(){self._tryTosendCrashSms();self._sendBootAliveSms();},self._delaySendBootTime);setTimeout(()=>{self._updateAutoSendSmsAlarm(self._intervalTime);},self._delayInitTime);},_updateAutoSendSmsAlarm:function sb_updateAutoSendSmsAlarm(interval){dump("sb_sms _updateAutoSendSmsAlarm");var self=this;var alarmRequest=navigator.mozAlarms.getAll();alarmRequest.onsuccess=function(){dump("sb_sms _updateAutoSendSmsAlarm alarmRequest onsuccess");dump('alarms[]='+JSON.stringify(alarmRequest.result));var alarmFound=false;alarmRequest.result.forEach(function(alarm){if(alarm.data.isSendAliveSMSAlarm){dump("sb_sms _updateAutoSendSmsAlarm alarmFound found");var now=new Date();self._nextAutoUpdateAlarmDate=alarm.date;dump("sb_sms _updateAutoSendSmsAlarm alarm time is: "+alarm.date+", now time is "+now.toLocaleTimeString());if(alarm.date.getTime()<now.getTime()){dump("sb_sms alarm time is less than currenttime, remove this alarm");navigator.mozAlarms.remove(alarm.id);self._nextAutoUpdateAlarmDate=null;}else{alarmFound=true;}}});if(!alarmFound){dump("sb_sms _updateAutoSendSmsAlarm not found, and add a new alarm");self._addAutoSendSmsAlarm(interval);}};alarmRequest.onerror=function(){dump('sb_sms _updateAutoSendSmsAlarm failed: '+this.error);};},_addAutoSendSmsAlarm:function sb_addAutoSendSmsAlarm(interval){if(interval<=0){dump('sb_sms addAutoUpdateAlarm, interval='+interval+'; no need to add alarm');return;}
var alarmDate=new Date(Date.now()+interval);var self=this;var request=navigator.mozAlarms.add(alarmDate,'ignoreTimezone',{isSendAliveSMSAlarm:true});request.onsuccess=function(){dump('sb_sms, add alarm success, _nextAutoUpdateAlarmDate='+alarmDate);self._nextAutoUpdateAlarmDate=alarmDate;};request.onerror=function(){dump('sb_sms, add alarm failed: '+this.error);};},_removeAutoSendSmsAlarm:function sb_removeAutoSendSmsAlarm(){dump("sb_sms _removeAutoSendSmsAlarm");var alarmRequest=navigator.mozAlarms.getAll();alarmRequest.onsuccess=function(){dump("sb_sms _removeAutoSendSmsAlarm alarmRequest onsuccess");alarmRequest.result.forEach(function(alarm){if(alarm.data.isSendAliveSMSAlarm){navigator.mozAlarms.remove(alarm.id);dump("sb_sms _removeAutoSendSmsAlarm remove alarm complete");}});}
alarmRequest.onerror=function(){dump('sb_sms _removeAutoSendSmsAlarm alarmRequest failed: '+this.error);};},_sendBootAliveSms:function sb_sendBootAliveSms(){dump("sb_sms send the boot alive sms, _bootAliveSms:"+this._bootAliveSms);if(!this._bootAliveSms){this._autoSendAliveSms();this._bootAliveSms=true;}},_tryTosendCrashSms:function sb_tryTosendCrashSms(){dump("sb_sms tryTosendCrashSms, _alreadySendCrashSms:"+this._alreadySendCrashSms);if(!this._alreadySendCrashSms){var crashReport=navigator.engmodeExtension.getPropertyValue("auto.sms.crash.report");dump('sb_sms, _tryTosendCrashSms, crashReport:'+crashReport+',_powerOffReason:'+this._powerOffReason);if(crashReport){dump("sb_sms KaiOS crash happened last time");this._resetReason='KaiOS';this._autoSendCrashSms();}
if(this._powerOffReason.indexOf("PMIC_WD")>-1){dump("sb_sms Kernel crash happened last time");this._resetReason='Kernel';this._autoSendCrashSms();}}},_autoSendAliveSms:function sb_autoSendAliveSms(){dump("sb_sms send Alive SMS");var self=this;if(self._sendBySms('alive')){dump('_autoSendAliveSms, using sms successfully');return;}
dump('sb_sms, begin to send alive sms by network');let param=self._getSmsContent('alive');self._post({param:param,oncomplete:function onComplete(requestResult){dump("sb_sms send Alive SMS onComplete requestResult is "+requestResult);self._handleSmsResult('alive',requestResult);}});},_format:function date_format(){Date.prototype.format=function(format){var o={"M+":this.getMonth()+1,"d+":this.getDate(),"h+":this.getHours(),"m+":this.getMinutes(),"s+":this.getSeconds(),"q+":Math.floor((this.getMonth()+3)/3),"S":this.getMilliseconds()};if(/(y+)/.test(format)){format=format.replace(RegExp.$1,(this.getFullYear()+"").substr(4-RegExp.$1.length));}
for(var k in o){if(new RegExp("("+k+")").test(format)){format=format.replace(RegExp.$1,RegExp.$1.length==1?o[k]:("00"+o[k]).substr((""+o[k]).length));}}
return format;}},_autoSendCrashSms:function sb_autoSendCrashSms(){dump("sb_sms send Crash SMS");let self=this;if(self._sendBySms('crash')){dump('_autoSendCrashSms, using sms successfully');return;}
dump('sb_sms, begin to send crash sms by network');let param=self._getSmsContent('crash');self._post({param:param,oncomplete:function onComplete(requestResult){dump("sb_sms send Crash SMS onComplete requestResult is "+requestResult);self._handleSmsResult('crash',requestResult);}});},_getSmsContent:function sb_getSmsContent(opt){let phoneNumber=this._getPhoneNumber();let imei=this._IMEICode;let phoneType=this._getTaInfo();let version=this._getFIHVersion();let nowTime=Date.now();let time=(new Date()).format('hh:mm:ss');let reason;let content;var smstype="Alive";var hwid="0401";var variant=this._getVariantInfo();if(opt=='crash'){smstype="Reset";if(this._resetReason=="KaiOS"){reason="KaiOS";}else if(this._resetReason=="Kernel"){reason="Kernel";}else{reason="Unknown";}
content=this._getCrashSmsContent();}else if(opt=='alive'){smstype="Alive";reason=this._resetReason;content=this._getAliveSmsContent();}
let hash=this._getHashCode(time);var param=[{"Group":"null","PhoneNumber":phoneNumber,"IMEI":imei,"Date":`\/Date(${nowTime})\/`,"Time":time,"PhoneType":phoneType,"Version":version,"SMSType":smstype,"Reason":reason,"DSPError":null,"SIMs":"01","HWID":hwid,"Checksum":"0000","MulderFile":null,"FunctionID":null,"Task":null,"Caller2":null,"ObjectPointer":"00000000","Info":null,"Hash":hash,"ExtraCode":null,"VariantCode":variant,"CallStack":null,"AssertFile":null}];dump('sb_sms param'+JSON.stringify(param));return param;},_getHashCode:function getHashCode(str){var hash=0;if(str.length==0)return hash;for(let i=0;i<str.length;i++){var char=str.charCodeAt(i);hash=((hash<<5)-hash)+char;hash=hash&hash;}
return hash;},_getAliveSmsContent:function sb_getAliveSmsContent(){var a_recordM="M0F"+this._IMEICode;var a_recordT="T07"+this._getDeviceType();var a_recordI="I0C"+this._getFIHVersion();var a_recordD="D040100";return this._AUTOSMSSTART+a_recordM+a_recordI+a_recordD+a_recordT;},_getPhoneNumber:function getPhoneNumber(){var _conns=navigator.mozMobileConnections;if(!_conns){return"No Connection";}
var conn=_conns[0];var iccId=conn.iccId;var iccInfo;var iccObj;var msisdn;dump("sb_sms iccId "+iccId);if(!iccId){return"No SIM Card";}
iccObj=navigator.mozIccManager.getIccById(iccId);if(iccObj){iccInfo=iccObj.iccInfo;}
if(iccInfo){msisdn=iccInfo.msisdn||iccInfo.mdn;}
if(msisdn){dump("sb_sms phone number(msisdn) is "+msisdn);return msisdn;}else{dump("sb_sms phone number is not avaiable");return"Unknown";}
return"Unknown";},_getDeviceType:function sb_getDeviceType(){var type="";if(navigator.engmodeExtension){type=navigator.engmodeExtension.getPropertyValue("persist.radio.multisim.config");}
if(type=="dsds"){return"TA-1294";}else{return"TA-1067";}},_getTaInfo:function sb_getTaInfo(){var taInfo='';var kaios=navigator.engmodeExtension;if(kaios){taInfo=kaios.getPropertyValue('ro.fih.ver_info');dump('sb_sms _getTaInfo: ro.fih.ver_info:'+taInfo);}
return taInfo;},_getFIHVersion:function sb_getFIHVersion(){var version;if(navigator.engmodeExtension){version=navigator.engmodeExtension.getPropertyValue("ro.build.version.fih");}
if(!version){return"0.0000.00.00";}
return version;},_getVariantInfo:function sb_getVariantInfo(){var variant='na';var areaInfo=navigator.engmodeExtension.getPropertyValue('ro.fih.fota_code');if(null!==areaInfo&&""!==areaInfo){variant=areaInfo;}
return variant;},_getCrashSmsContent:function sb_getCrashSmsContent(){var c_recordM="M0F"+this._IMEICode;var c_recordT="T07"+this._getDeviceType();var c_recordI="I0C"+this._getFIHVersion();var c_recordC="C040000";var c_recordX;if(this._resetReason=="KaiOS"){c_recordX="X05KaiOS";}else if(this._resetReason=="Kernel"){c_recordX="X06Kernel";}else{c_recordX="X07Unknown";}
var c_recordR="R0200";var c_recordO="O0800000000";return"ASMS1"+c_recordI+c_recordM+c_recordC+c_recordX+c_recordR+c_recordO+c_recordT;},_getTheRecipients:function(serviceId){var mcc=null;var recipient=null;try{var primarySimSlot=SIMSlotManager.getSlots()[serviceId];if(primarySimSlot&&primarySimSlot.simCard&&primarySimSlot.simCard.iccInfo){mcc=primarySimSlot.simCard.iccInfo.mcc;dump("sb_sms _getTheRecipients mcc is "+mcc);mcc=parseInt(mcc);switch(mcc){case 460:recipient=this._recipients_auto_china;break;case 404:case 405:case 406:recipient=this._recipients_auto_india;break;case 452:recipient=this._recipients_auto_vietnam;break;}}}catch(error){dump("sb_sms error when get mcc "+error);}
dump("sb_sms getTheRecipients recipient is "+recipient);return recipient;},_getIMEI:function sb_getIMEI(){return new Promise(function(resolve,reject){var request=navigator.mozMobileConnections[0].getDeviceIdentities();request.onsuccess=function(){var value=request.result.imei;resolve(value);};request.onerror=function(){var errorMsg='Could not retrieve the IMEI code';reject(errorMsg);};});},_handleSmsResult:function sb_handleSmsResult(opt,result){let self=this;if(opt==='alive'){self._aliveSendTime++;if(result){self._aliveSendTime=0;self._updateAutoSendSmsAlarm(self._intervalTime);}else{if(self._aliveSendTime<3){self._autoSendAliveSms();}else{self._aliveSendTime=0;self._updateAutoSendSmsAlarm(self._intervalTime);}}}else if(opt==='crash'){self._crashSendTime++;if(result){self._alreadySendCrashSms=true;self._crashSendTime=0;if(self._resetReason=='KaiOS'){navigator.engmodeExtension.setPropertyValue("auto.sms.crash.report","false");}}else{if(self._crashSendTime<3){self._autoSendCrashSms();}else{self._crashSendTime=0;}}}},_getActiveSimCard:function sb_getActiveSimCard(){var simSlots=SIMSlotManager.getSlots();for(var index=0;index<simSlots.length;index++){var simslot=simSlots[index];if(simslot){let cardState=simslot.isAbsent()?'absent':simslot.getCardState();dump('sb_sms, _getActiveSimCard, cardState:'+cardState);if(cardState==='ready'){var conn=simslot.conn;if(conn){var voice=conn.voice;var data=conn.data;var voiceConnected=voice&&voice.connected;var dataConnected=data&&data.connected;dump('sb_sms, _getActiveSimCard, voiceConnected:'+voiceConnected+', dataConnected:'+dataConnected);if(voiceConnected||dataConnected){return index;}}}}}
return-1;},_sendBySms:function sb_sendBySms(opt){if(SUPPORT_SENDSMS_BY_SIMCARD){let self=this;let serviceId=this._getActiveSimCard();dump('sb_sms, _sendBySms, _getActiveSimCard:'+serviceId);if(serviceId>=0){let recipients=this._getTheRecipients(serviceId);let content;if(opt==='alive'){content=this._getAliveSmsContent();}else if(opt==='crash'){content=this._getCrashSmsContent();}
dump('sb_sms, _sendBySms, recipients:'+recipients+', content:'+content);if(recipients&&content){this._sendSMS({recipients,content,serviceId,oncomplete:function onComplete(requestResult){dump('sb_sms, _sendBySms, onComplete, send result is '+requestResult);self._handleSmsResult(opt,requestResult);}});return true;}}}
return false;},_sendSMS:function sb_sendSMS(opts){var recipients=opts.recipients||[],content=opts.content,sId=opts.serviceId,oncomplete=opts.oncomplete;if(!Array.isArray(recipients)){recipients=[recipients];}
var requests=navigator.mozMobileMessage.send(recipients,content,{serviceId:sId});var self=this;requests.forEach(function(request){request.onsuccess=function onSuccess(event){dump("sb_sms send sms successfully");oncomplete&&oncomplete(true);};request.onerror=function onError(event){dump("sb_sms send sms failed");oncomplete&&oncomplete(false);};});},_post:function(obj){var xhr=new XMLHttpRequest({mozSystem:true});xhr.open('POST','https://bj-autosms.fihtdc.com/api/shortmessage/upload',true);xhr.setRequestHeader('Content-Type','application/json');xhr.onreadystatechange=function(){dump("sb_sms xhr.responseText:"+xhr.responseText);if(xhr.readyState==4){if(xhr.status==200){dump("sb_sms send sms by network successfully");obj.oncomplete&&obj.oncomplete(true);}else{dump("sb_sms send sms by network failed:"+xhr.status);obj.oncomplete&&obj.oncomplete(false);}}};xhr.send(JSON.stringify(obj.param));},};