
(function(exports){'use strict';var _id=0;var BrowserNavigationWidgets=function(app){this.app=app;this.instanceID=_id++;this.containerElement=app.element;this._zoomScaleIndex=this.DEFAULT_ZOOM_SCALE_INDEX;this.render();};BrowserNavigationWidgets.prototype=Object.create(exports.BaseUI.prototype);BrowserNavigationWidgets.prototype.CLASS_NAME='BrowserNavigationWidgets';BrowserNavigationWidgets.prototype.EVENT_PREFIX='browser-scroll-indicator';BrowserNavigationWidgets.prototype.DEBUG=false;BrowserNavigationWidgets.prototype.ZOOM_SCALES=Object.freeze([0.33,0.5,0.67,1.0,1.5,2.0]);BrowserNavigationWidgets.prototype.DEFAULT_ZOOM_SCALE_INDEX=3;BrowserNavigationWidgets.prototype.view=function(){var className=this.CLASS_NAME+this.instanceID;return`<div class="scroll-direction-indicator hidden" id="${className}">
                <div class="scroll-direction-icon top"></div>
                <div class="scroll-direction-icon left"></div>
                <div class="scroll-direction-icon right"></div>
                <div class="scroll-direction-icon bottom"></div>
            </div>`;};BrowserNavigationWidgets.prototype.render=function(){this.publish('willrender');this.app.element.insertAdjacentHTML('afterbegin',this.view());this._fetchElements();this._registerEvents();this.publish('rendered');};BrowserNavigationWidgets.prototype._fetchElements=function(){this.navigationModeIndicator=this.containerElement.querySelector('.scroll-direction-indicator');};BrowserNavigationWidgets.prototype._registerEvents=function(){this.app.element.addEventListener('_opened',this);this.app.element.addEventListener('_loaded',this);this.app.element.addEventListener('_closing',this);this.app.element.addEventListener('_scrollerModeChanged',this);this.app.browser.element.addEventListener('mozbrowserlocationchange',this);window.addEventListener('will-shutdown',this);window.addEventListener('soundManagerShow',this);window.addEventListener('soundManagerHide',this);};BrowserNavigationWidgets.prototype.handleEvent=function(evt){switch(evt.type){case'_loaded':this.setNavigationMode('spatial');break;case'_scrollerModeChanged':this.udpateNavigationMode();break;case'mozbrowserlocationchange':if(!evt.detail.sameDocument){this.resetZoom();this.setNavigationMode('spatial');}
break;case'will-shutdown':case'soundManagerShow':this.app.toggleSpatialNavigation(false);break;case'soundManagerHide':this.app.toggleSpatialNavigation(true);break;}};BrowserNavigationWidgets.prototype._unregisterEvents=function(){this.app.element.removeEventListener('_opened',this);this.app.element.removeEventListener('_loaded',this);this.app.element.removeEventListener('_closing',this);this.app.element.removeEventListener('_scrollerModeChanged',this);this.app.browser.element.removeEventListener('mozbrowserlocationchange',this);window.removeEventListener('will-shutdown',this);window.removeEventListener('soundManagerShow',this);window.removeEventListener('soundManagerHide',this);};BrowserNavigationWidgets.prototype.zoom=function(direction){var oldScale=this.ZOOM_SCALES[this._zoomScaleIndex];var scale;switch(direction){case'in':this._zoomScaleIndex=(this._zoomScaleIndex+1<this.ZOOM_SCALES.length)?this._zoomScaleIndex+1:this.ZOOM_SCALES.length-1;break;case'out':this._zoomScaleIndex=(this._zoomScaleIndex-1>=0)?this._zoomScaleIndex-1:0;break;}
scale=this.ZOOM_SCALES[this._zoomScaleIndex];if(scale!==oldScale){this._updateZoomScale(scale);}};BrowserNavigationWidgets.prototype.resetZoom=function(){if(this._zoomScaleIndex!==this.DEFAULT_ZOOM_SCALE_INDEX){this._zoomScaleIndex=this.DEFAULT_ZOOM_SCALE_INDEX;var scale=this.ZOOM_SCALES[this._zoomScaleIndex];this._updateZoomScale(scale);}};BrowserNavigationWidgets.prototype._updateZoomScale=function(scale){if(typeof scale==='number'){this.app.zoom(scale);}};BrowserNavigationWidgets.prototype.setNavigationMode=function(mode){this.debug('setNavigationMode(): mode = '+mode);switch(mode){case'spatial':this.app.toggleScrollNavigation(false);break;case'toggle':var enabled=!getBrowserProperty(this.app.browser.element,'touchPanningSimulationEnabled');if(enabled&&!document.mozFullScreen){this.app.toggleScrollNavigation(enabled);}else if(!enabled){this.app.toggleScrollNavigation(enabled);}
break;}};BrowserNavigationWidgets.prototype.udpateNavigationMode=function(){var isScrollMode=getBrowserProperty(this.app.browser.element,'touchPanningSimulationEnabled');this.debug('udpateNavigationMode(): isScrollMode = '+isScrollMode);if(isScrollMode){this.navigationModeIndicator.classList.remove('hidden');}else{this.navigationModeIndicator.classList.add('hidden');}};BrowserNavigationWidgets.prototype.scroll=function(direction){switch(direction){case'top':this.app.browser.element.scrollToTop();break;case'down':this.app.browser.element.scrollToBottom();break;}};exports.BrowserNavigationWidgets=BrowserNavigationWidgets;}(window));