'use strict';(function(exports){let defaultSim=0;let lastMcc='0';const NO_SIM_MCC='000';const NO_SIM_MNC='00';function debug(msg){console.log('[clientIdlog] '+msg);}
function parseClientIdsConfig(){return LazyLoader.getJSON('/resources/google_clientIds/google_clientIds.json').then(clientIds=>{return Promise.resolve(clientIds);},()=>{return Promise.reject('read google_clientIds.json failed.');});}
function configGoogleClientId(mcc,mnc){if(mcc===lastMcc){return;}
lastMcc=mcc;debug(`configGoogleClientId -----> ${mcc}`);const google_client_id='google.client_id';const kaidc_google_client_id='kaidc.google-client-id';let Settings=navigator.mozSettings;parseClientIdsConfig().then((clientIds)=>{let defaultClientId=clientIds.default_clientId;let googleClientIds=clientIds.google_clientIds;let kaiosDefault=clientIds.kaios_default;let shouldConfigClientId=defaultClientId;let matchClentId=googleClientIds.filter((clientId)=>{return(clientId.mcc===mcc);});shouldConfigClientId=matchClentId.length>0?matchClentId[0].clientId:(mcc===NO_SIM_MCC?defaultClientId:kaiosDefault);debug(`shouldConfigClientId -> ${shouldConfigClientId}`);Settings.createLock().get(kaidc_google_client_id).then((kResult)=>{debug(`Get kaidc_google_client_id success, details is ${JSON.stringify(kResult)}`);if(!kResult||!Object.keys(kResult).length){debug('It\'s first time to configure google client id.');let obj={};obj[google_client_id]=shouldConfigClientId;Settings.createLock().set(obj).then(()=>{debug(`Set google_client_id success`);});if(matchClentId.length>0){let kaidcObj={};kaidcObj[kaidc_google_client_id]=JSON.stringify(obj);Settings.createLock().set(kaidcObj).then(()=>{debug(`Set kaidc_google_client_id success`);window.removeEventListener('simslot-iccinfochange',handleSimCardState);},(reason)=>{debug(`Set kaidc_google_client_id fail, reason is ${reason}`);});}}else{debug('It\'s not the first time to configure google client id.');}},(reason)=>{debug(`Get kaidc_google_client_id fail, reason is ${reason}`);});},(reason)=>{debug(`parse google_clientIds.json Config fail, reason is ${reason}`);});}
function getSIMInfo(){let simInfo={network:null,icc:null};if(SIMSlotManager.noSIMCardConnectedToNetwork()){return simInfo;}
let slots=SIMSlotManager.getSlots().filter(function(slot){return!slot.isAbsent()&&!slot.isLocked();});if(slots.length===0){return simInfo;}
let slot=slots[defaultSim]?slots[defaultSim]:slots[0];let conn=slot&&slot.conn;if(!conn){return simInfo;}
let iccObj=navigator.mozIccManager.getIccById(conn.iccId);debug(`iccCard.cardState -> ${iccObj.cardState}`);let iccInfo=iccObj?iccObj.iccInfo:null;let voiceNetwork=conn.voice?conn.voice.network:null;if(!iccInfo&&!voiceNetwork){return simInfo;}
simInfo.network=MobileOperator.userFacingInfo(conn);debug('voiceNetwork='+voiceNetwork);if(voiceNetwork){simInfo.network.mnc=voiceNetwork.mnc;simInfo.network.mcc=voiceNetwork.mcc;}
if(iccInfo){simInfo.icc={mnc:iccInfo.mnc,mcc:iccInfo.mcc,spn:iccInfo.spn};}
return simInfo;}
function handleSimCardState(){let simInfo=getSIMInfo();if(simInfo&&simInfo.icc&&simInfo.icc.mcc){let mcc=simInfo.icc.mcc;let mnc=simInfo.icc.mnc;debug(`handleSimCardStateChange mcc=${mcc} mnc=${mnc}`);configGoogleClientId(mcc,mnc);}}
window.addEventListener('applicationready',function appListReady(event){window.removeEventListener('applicationready',appListReady);debug(`applicationready`);var skuid='';skuid=navigator.engmodeExtension.getPropertyValue('ro.boot.skuid');debug('miao skuid='+skuid);if(skuid==='600WW'){return;}
configGoogleClientId(NO_SIM_MCC,NO_SIM_MNC);navigator.mozSettings.createLock().get('ril.data.defaultServiceId').then((result)=>{if(result){defaultSim=result['ril.data.defaultServiceId'];debug('this.defaultSim is '+defaultSim);}
handleSimCardState();window.addEventListener('simslot-iccinfochange',handleSimCardState);});});}(window));