'use strict';let isDeepCleanupMemory=navigator.memoryCleanerManager&&navigator.memoryCleanerManager.status&&navigator.memoryCleanerManager.status.includes('stage');var CustomLogoPath=(function(){const DEFAULT_RESOURCES={poweron:{video:'/resources/power/carrier_power_on.mp4',image:'/resources/power/carrier_power_on.png'},poweroff:{video:'/resources/power/carrier_power_off.mp4',image:'/resources/power/carrier_power_off.png'},oslogo:{video:null,image:'/shared/resources/branding/initlogo.png'},cleanup:{video:'/resources/power/clean_up_memory.mp4',image:null},deepcleanuplogo:{video:null,image:'/resources/power/deep_clean_up_memory_start.png'},deepcleanup:{video:'/resources/power/deep_clean_up_memory.mp4',image:null}};var _poweron={};var _poweroff={};var _oslogo={};var _cleanup={};function setDefaultValues(){_poweron.video=isDeepCleanupMemory?DEFAULT_RESOURCES.deepcleanup.video:DEFAULT_RESOURCES.poweron.video;_poweron.image=DEFAULT_RESOURCES.poweron.image;_poweroff.video=DEFAULT_RESOURCES.poweroff.video;_poweroff.image=DEFAULT_RESOURCES.poweroff.image;_cleanup.video=DEFAULT_RESOURCES.cleanup.video;_cleanup.image=DEFAULT_RESOURCES.cleanup.image;var skuid='';skuid=navigator.engmodeExtension.getPropertyValue('ro.boot.skuid');dump(`init_logo:setDefaultValues skuid: `+skuid);var defaultLogoImage=null;if(skuid==='62HMX'){defaultLogoImage='/shared/resources/branding/initlogo_telcel.png';_poweroff.video='/resources/power/carrier_power_off_telcel.mp4';}else if(skuid==='62GMX'){defaultLogoImage='/shared/resources/branding/initlogo_claro.png';_poweroff.video='/resources/power/carrier_power_off_claro.mp4';}else{defaultLogoImage='/shared/resources/branding/initlogo.png';}
_oslogo.image=isDeepCleanupMemory?DEFAULT_RESOURCES.deepcleanuplogo.image:defaultLogoImage;}
function init(aNext){setDefaultValues();aNext&&aNext();}
return{get poweron(){return _poweron;},get poweroff(){return _poweroff;},get oslogo(){return _oslogo;},get cleanup(){return _cleanup;},init:init};})();var InitLogoHandler={name:'InitLogoHandler',ready:false,finished:false,animated:false,readyCallBack:null,logoLoader:null,EVENT_PREFIX:'initlogo',publish:function(evtName){window.dispatchEvent(new CustomEvent(this.EVENT_PREFIX+evtName,{detail:this}));},get carrierLogo(){delete this.carrierLogo;return(this.carrierLogo=document.getElementById('carrier-logo'));},get osLogo(){delete this.osLogo;return(this.osLogo=document.getElementById('os-logo'));},cleanupMemory(){if(!this.cleanDOM){this.cleanDOM=document.getElementById('cleanup');const transCleanup=()=>{this.cleanDOM.innerHTML='';this.cleanDOM.classList.remove('fadeOut');this.cleanDOM.classList.remove('active');}
this.cleanDOM.addEventListener('transitionend',transCleanup);}
this.cleanDOM.classList.add('active');this.loader=new LogoLoader(CustomLogoPath.cleanup);this.loader.onload=()=>{this.cleanDOM.appendChild(this.loader.element);this.loader.element.onended=()=>{this.loader=null;navigator.minimizeMemoryUsage&&navigator.minimizeMemoryUsage();window.requestAnimationFrame(()=>{this.cleanDOM.classList.add('fadeOut');});};this.loader.element.play();};},init:function ilh_init(logoLoader){var self=this;this._transOsLogo=this.transOsLogo.bind(this);window.addEventListener('keydown',this);window.addEventListener('ftuopen',this);window.addEventListener('ftuskip',this);window.addEventListener('hierarchychanged',()=>{if(attentionWindowManager.isActive()){if(isDeepCleanupMemory){this.logoLoader.element.pause();this.transOsLogo();}else if(this.loader){this.loader=null;navigator.minimizeMemoryUsage&&navigator.minimizeMemoryUsage();window.requestAnimationFrame(()=>{this.cleanDOM.classList.add('fadeOut');});}}});this.logoLoader=logoLoader;logoLoader.onnotfound=function(){self._removeCarrierPowerOn();self._playDefaultPowerOnSound();};this.oslogoLoader=new LogoLoader(CustomLogoPath.oslogo);this.oslogoLoader.onload=()=>{if(this.osLogo){this._appendOsLogo();}else{document.addEventListener('DOMContentLoaded',()=>{this.osLogo=document.getElementById('os-logo');this._appendOsLogo();});}};logoLoader.onload=()=>{if(this.carrierLogo){this._appendCarrierPowerOn();}else{document.addEventListener('DOMContentLoaded',this._appendCarrierPowerOn.bind(this));}};if(window.Service){Service.request('registerHierarchy',this);Service.register('cleanMemory',this);}},_playDefaultPowerOnSound:function(){var self=this;var skuid='';skuid=navigator.engmodeExtension.getPropertyValue('ro.boot.skuid');dump("init_logo:setDefaultValues skuid: "+skuid);if(skuid==='62HMX'||skuid==='62GMX'){return;}
window.addEventListener('mozChromeEvent',function startOsLogoSound(e){if(e.detail.type!=='system-first-paint'){return;}
var deletePowerOnAudio=function(){self.osLogoSoundElement.remove();delete self.osLogoSoundElement;};self.osLogoSoundElement=document.createElement('audio');self.osLogoSoundElement.src='/resources/sounds/poweron-sound.ogg';self.osLogoSoundElement.preload='auto';self.osLogoSoundElement.mozAudioChannelType='publicnotification';self.osLogoSoundElement.addEventListener('ended',deletePowerOnAudio);self.osLogoSoundElement.addEventListener('error',deletePowerOnAudio);self.osLogoSoundElement.addEventListener('canplaythrough',function(){self.osLogoSoundElement.play();},false);self.osLogo.appendChild(self.osLogoSoundElement);});},respondToHierarchyEvent:function(evt){if(this['_handle_'+evt.type]){return this['_handle_'+evt.type](evt);}else{return true;}},_handle_home:function ilh_handle_home(){if(this.isActive()){return false;}
return true;},_handle_holdhome:function ilh_handle_holdhome(){if(this.isActive()){return false;}
return true;},handleEvent:function ilh_handleEvent(evt){if(evt.type==='keydown'){evt.stopPropagation();evt.preventDefault();return;}
this.animate();},_removeCarrierPowerOn:function ilh_removeCarrierPowerOn(){var self=this;if(this.carrierLogo&&this.carrierLogo.parentNode){this.carrierLogo.parentNode.removeChild(self.carrierLogo);this._setReady();}else{document.addEventListener('DOMContentLoaded',function(){if(self.carrierLogo){self.carrierLogo.parentNode.removeChild(self.carrierLogo);}
self._setReady();});}},_appendCarrierPowerOn:function ilh_appendCarrierPowerOn(){this.carrierLogo.appendChild(this.logoLoader.element);this._setReady();var elem=this.logoLoader.element;if(elem&&elem.tagName.toLowerCase()!=='video'){this._playDefaultPowerOnSound();}},_appendOsLogo:function ilh_appendCarrierPowerOn(){var carrierLogo=document.getElementById('carrier-logo');if(carrierLogo){this.osLogo.insertBefore(this.oslogoLoader.element,carrierLogo);}else{this.osLogo.appendChild(this.oslogoLoader.element);}},_setReady:function ilh_setReady(){this.ready=true;var elem=this.logoLoader.element;var osLogoElem=this.oslogoLoader.element;if(elem&&elem.tagName.toLowerCase()=='video'){window.addEventListener('mozChromeEvent',function startVideo(e){if(e.detail.type==='system-first-paint'){window.removeEventListener('mozChromeEvent',startVideo);if(elem&&elem.ended===false){elem.play();if(isDeepCleanupMemory&&navigator.memoryCleanerManager.status!=='stage2'){navigator.memoryCleanerManager.status='stage2';osLogoElem.src='/resources/power/deep_clean_up_memory_end.png';}
elem.onended=function(){elem.classList.add('hide');};}}});}
if(this.readyCallBack){this.readyCallBack();this.readyCallBack=null;}
this.publish('-activated');},_waitReady:function ilh_waitReady(callback){this.readyCallBack=callback;},isActive:function(){return this.ready&&!this.animated;},removeEvenListener:function(){window.removeEventListener('keydown',this);window.removeEventListener('ftudone',this);window.removeEventListener('skip',this);},transOsLogo:function(){this.osLogo.removeEventListener('transitionend',this._transOsLogo);this.osLogo.parentNode.removeChild(this.osLogo);this.oslogoLoader.element.removeAttribute('src');delete this.oslogoLoader;delete this.osLogo;this.publish('-deactivated');Service.request('unregisterHierarchy',this);window.performance.mark('osLogoEnd');this.finished=true;this.removeEvenListener();var evt=new CustomEvent('logohidden');window.dispatchEvent(evt);window.ExternalScreenManager.send(evt);if(isDeepCleanupMemory){isDeepCleanupMemory=false;navigator.memoryCleanerManager.status='completed';}},animate:function ilh_animate(){var self=this;if(!this.ready){this._waitReady(this.animate.bind(this));return;}
if(this.animated)
return;this.animated=true;if(!self.logoLoader.found){self.osLogo.classList.add('hide');}else{self.carrierLogo.className='transparent';var elem=self.logoLoader.element;if(elem.tagName.toLowerCase()==='video'&&!elem.ended){elem.play();if(isDeepCleanupMemory&&navigator.memoryCleanerManager.status!=='stage2'){navigator.memoryCleanerManager.status='stage2';this.oslogoLoader.element.src='/resources/power/deep_clean_up_memory_end.png';}
elem.onended=function(){elem.classList.add('hide');};}else{elem.classList.add('hide');}
self.carrierLogo.addEventListener('transitionend',function transCarrierLogo(evt){evt.stopPropagation();self.carrierLogo.removeEventListener('transitionend',transCarrierLogo);elem.removeAttribute('src');if(elem.tagName.toLowerCase()=='video'){elem.load();}
self.carrierLogo.parentNode.removeChild(self.carrierLogo);delete self.carrierLogo;self.osLogo.classList.add('hide');self.carrierPowerOnElement=null;});}
if(window.Service&&Service.query('ScreenManager.lidOpened')===false){this.transOsLogo();}else if(self.osLogo){self.osLogo.addEventListener('transitionend',this._transOsLogo);}
if(isDeepCleanupMemory&&elem.ended){this.transOsLogo();}}};CustomLogoPath.init(function(){InitLogoHandler.init(new LogoLoader(CustomLogoPath.poweron));});