'use strict';const origin='app://keyboard.gaiamobile.org';const url=origin+'/index.html';const manifestURL=origin+'/manifest.webapp';const IGNORED_INPUT_TYPES={'select-one':true,'select-multiple':true,'date':true,'time':true,'datetime':true,'datetime-local':true};window.KeyboardManager={_onDebug:false,_debug:function km_debug(msg){if(this._onDebug){console.log('[Keyboard Manager] '+msg);}},name:'KeyboardManager',get _appFrame(){return this.keyboard.querySelector('iframe');},init:function km_init(){window.addEventListener('mozChromeEvent',this);window.addEventListener('iac-spell-dialog',this);window.Service.registerState('isActivated',this);window.Service.register('kill',this);this.keyboard=document.getElementById('keyboard-app');this.isActivated=false;LazyLoader.load(['shared/js/keypad_helper.js'],function(){this.keypadHelper=new KeypadHelper();this.keypadHelper.start();this.keypadHelper.getActiveLayout().then((layout)=>{this._setActiveLayout(layout);this.launchKeyboard();});this.keypadHelper.setActiveModeChangedCallback(this._publishModeChanged.bind(this));this.keypadHelper.setLayoutsChangedCallback(this._handleLayoutsChanged.bind(this));this.keypadHelper.setActiveLayoutChangedCallback(this._handleLayoutChanged.bind(this));}.bind(this));},launchKeyboard:function(){this.keyboard.innerHTML=`
    <iframe
      mozbrowser='true'
      remote='true'
      mozapptype='inputmethod'
      mozpasspointerevents='true'
      ignoreuserfocus='true'
      src='${origin}/index.html#en'
      mozapp='${manifestURL}'
    >
    </iframe>`;this.registerKbEvents();},registerKbEvents:function(){this._appFrame.addEventListener('mozbrowserresize',this);this._appFrame.addEventListener('mozbrowsererror',this);},kill:function(){this.deactivateKeyboard();this.keyboardKilled=true;this.keyboard.innerHTML='';},_setActiveLayout:function(activeLayout){this.activeLayout=activeLayout;},_handleLayoutsChanged:function(layouts){let newLanguages=[];for(let key in layouts){if(layouts[key]){newLanguages.push(key);}}
if(newLanguages.indexOf(this.activeLayout)===-1){this.keypadHelper.setActiveLayout(newLanguages[0]);}},_handleLayoutChanged:function(layout){var languages=this.keypadHelper.DISPLAY_LANGUAGES[layout];this.activeLayout=layout;this._showToaster({text:languages});},publish:function(type,detail){const eventInitDict={bubbles:true,cancelable:true,detail:detail};const evt=new CustomEvent(type,eventInitDict);document.body.dispatchEvent(evt);},_publishModeChanged:function(value){var idMap={'abc':'ime-lowercase','ABC':'ime-uppercase','123':'ime-number','Abc':'ime-capitalize','T9':'ime-predictive'};var displayName=this.keypadHelper.DISPLAY_LANGUAGES[this.activeLayout];var iconText=this.keypadHelper.LANGUAGES_ICON_TEXT[this.activeLayout];this.publish('keyboard-mode-changed',{mode:value.mode,iconText:iconText,activeLayout:this.activeLayout});if(value.byUser){var ariaLabel=navigator.mozL10n.get(idMap[value.mode]);if(iconText&&value.mode==='abc'){this._showToaster({text:displayName});return;}
if(value.mode==='T9'){if(this.activeLayout.indexOf('chinese')>-1||this.activeLayout==='korean'){this._showToaster({text:displayName,ariaLabel:ariaLabel});}else{this._showToaster({text:ariaLabel,ariaLabel:ariaLabel});}
return;}
this._showToaster({text:value.mode,ariaLabel:ariaLabel});}},_showToaster:function(option){Service.request('SystemToaster:show',{text:option.text,ariaLabel:option.ariaLabel,onceFlag:'IME',timeout:1500});},_inputFocusChange:function km_inputFocusChange(evt){const type=evt.detail.inputType;if(!type||type in IGNORED_INPUT_TYPES||'blur'===type){this.deactivateKeyboard();}else{if(this.keyboardKilled){this.launchKeyboard();this.keyboardKilled=false;}
this.activateKeyboard();}},activateKeyboard:function(){this.isActivated=true;this.publish('keyboard-activated');this.keyboard.style.opacity=1;this._appFrame.setInputMethodActive(true);},deactivateKeyboard:function(){this.isActivated=false;this.publish('keyboard-deactivated');this.keyboard.style.opacity=0;this._appFrame.setInputMethodActive(false);},handleEvent:function km_handleEvent(evt){switch(evt.type){case'mozChromeEvent':switch(evt.detail.type){case'inputmethod-contextchange':this._inputFocusChange(evt);break;}
break;case'mozbrowsererror':if(evt.detail.type==='fatal'){this.keyboardKilled=true;this.deactivateKeyboard();}
break;case'iac-spell-dialog':if(evt.detail==='voice-input-ftu'){Service.request('DialogService:show',{type:'alert',style:'google',content:'ime-voice-input-messsage'});}else{Service.request('DialogService:show',{type:'prompt',content:'ime-insert-word',inputMode:'spell',maxLength:45,ok:'ok',cancel:'cancel',onOk:()=>{this.deactivateKeyboard();navigator.mozInputMethod.removeFocus();},onCancel:()=>{this.deactivateKeyboard();navigator.mozInputMethod.removeFocus();}});}
break;}}};