
(function(exports){'use strict';var BrowserPinSitesDataStore=function(){this.onChangeFN=null;this.start();};BrowserPinSitesDataStore.prototype={DEBUG:false,name:'browserPinSitesDataStore',STORE_NAME:'browser_store',MAXIMUM_NUMBER_OF_PINNED_SITES:6,start:function(){return this._getStore();},stop:function(){},_getStore:function(){if(this._store){return Promise.resolve(this._store);}
return new Promise((resolve,reject)=>{navigator.getDataStores(this.STORE_NAME).then((stores)=>{if(typeof this.onChangeFN==='function'){stores[0].addEventListener('change',this.onChangeFN);}
this._store=stores[0];resolve(stores[0]);},()=>{var reason='Unable to get datastore "'+this.STORE_NAME+'"';reject(reason);console.warn(reason);});});},getPinSites:function(){return this._getStore().then((store)=>{return store.get('pinned_sites');});},savePinSite:function(pinSite,targetIndex=-1){return this.getPinSites().then((pinSites)=>{let result='unknown';let replace=false;if(pinSites){if(targetIndex===-1){pinSites.some((site,index)=>{if(site.url===pinSite.url){targetIndex=index;return true;}});}else{replace=true;}
if(replace){result='pinCompleted';pinSites.splice(targetIndex,1,pinSite);}else{if(targetIndex>-1){result='wasPinnedBefore';pinSites.splice(targetIndex,1);pinSites.unshift(pinSite);}else if(pinSites.length<this.MAXIMUM_NUMBER_OF_PINNED_SITES){result='pinCompleted';pinSites.unshift(pinSite);}else{result='pinnedSitesOverLimit';return Promise.resolve(result);}}}else{result='pinCompleted';pinSites=[];pinSites.push(pinSite);}
return this.savePinSites(pinSites).then(()=>{return Promise.resolve(result);},(reason)=>{return Promise.reject(reason);});});},appendPinSites:function(appendingPinSites){if(!Array.isArray(appendingPinSites)){Promise.reject('not array');}
return this.getPinSites().then((pinSites)=>{if(pinSites){pinSites=pinSites.concat(appendingPinSites);}else{pinSites=appendingPinSites;}
return this.savePinSites(pinSites);});},savePinSites:function(pinSites){if(!Array.isArray(pinSites)){Promise.reject('not array');}
return this._getStore().then((store)=>{return store.put(pinSites,'pinned_sites');});},removeFromPinSites:function(url,targetIndex=-1,placeholder=false){if(!url){return Promise.reject();}
return this.getPinSites().then((pinSites)=>{if(targetIndex<0){pinSites.some((site,index)=>{if(site.url===url){targetIndex=index;return true;}});}
if(targetIndex>-1){if(placeholder){pinSites.splice(targetIndex,1,null);}else{pinSites.splice(targetIndex,1);}}
return this.savePinSites(pinSites);});},set onChange(onChange){this.onChangeFN=onChange;}};exports.BrowserPinSitesDataStore=BrowserPinSitesDataStore;}(window));