'use strict';const DEL_CHAR='\b';const SEND_CHAR='\n';const SPECIAL_MESSAGE=String.fromCharCode(239)+String.fromCharCode(191)+
String.fromCharCode(189);function RttView(call,callId,name,durationNode){this.call=call;this.callId=callId;this.name=name;this.durationNode=durationNode;this.view=null;this.sendIntervalTime=1000;this.receiveIntervalTime=1300;this.nextMesageId=0;this.appendSentMessage=true;this.appendReceivedMessage=true;this.showLastSentMessageTimer=null;this.inputTime=null;this.receiveTime=null;this.backupMsg='';this.call.onrttmessage=(req)=>{this.receiveMessage(req.message);};this.addView();}
RttView.prototype.addView=function rv_addView(){this.view=document.getElementById('rtt-view-template').cloneNode(true);this.view.id='';this.view.setAttribute('call-id',this.callId);this.messageInput=this.view.querySelector('.messages-input');this.messageInput.addEventListener('keydown',this.handleInput.bind(this));this.messageInput.placeholder=navigator.mozL10n.get('message');let callscreen=document.getElementById('call-screen');callscreen.appendChild(this.view);let name=this.view.querySelector('.name');let time=this.view.querySelector('.time');name.textContent=this.name;time.textContent=' ('+this.durationNode.textContent+')';setInterval(()=>{time.textContent=' ('+this.durationNode.textContent+')';},1000);this.messageInput.oninput=this.onMessageInput.bind(this);};RttView.prototype.show=function rv_show(){if(this.view){this.view.classList.add('display');this.messageInput.focus();this.messageInput.onblur=()=>{if(this.view.classList.contains('display')&&!CallScreen.isBtMenuDisplayed()){setTimeout(()=>{this.messageInput.focus();});}};}};RttView.prototype.hide=function rv_hide(){this.view.classList.remove('display');};RttView.prototype.remove=function rv_remove(){if(this.view.parentNode){this.view.parentNode.removeChild(this.view);}
RttCache.clearCache(this.callId);};RttView.prototype.onMessageInput=function rv_onMessageInput(evt){clearTimeout(this.inputTime);if(evt.isComposing){this.call.sendRttMessage(' '+DEL_CHAR);return;}
this.inputTime=setTimeout(()=>{this.resetInput();},this.sendIntervalTime);if(this.appendSentMessage){console.log('RTT append new sent message');if(!this.messageInput.value){return;}
this.appendSentMessage=false;this.activeSentMessageId=this.appendMessage({direction:'sent',body:this.messageInput.value});}else{this.updateMessage(this.activeSentMessageId,this.messageInput.value);}
this.sendMessage(this.messageInput.value);if(!this.messageInput.value){this.resetInput();}};RttView.prototype.receiveMessage=function rv_receiveMessage(message){console.log('RTT receiveMessage '+message);for(let i=0;i<message.length;i++){console.log('RTT receiveMessage transfor: '+message.charCodeAt(i));}
message=message.replace(/\n/g,'');message=message.replace(SPECIAL_MESSAGE,'');if(!message){return;}
if(this.receiveTime){clearTimeout(this.receiveTime);}
this.receiveTime=setTimeout(()=>{this.resetReceive();},this.receiveIntervalTime);let messageSanitized=this.sanitizedMessage(message);for(let i=0;i<messageSanitized.del.length;i++){this.appendReceivedMessage=false;let lastMessage=RttCache.getLastMessage(this.callId,'received');if(lastMessage&&lastMessage.id!==undefined){this.activeReceivedMessageId=lastMessage.id;this.updateMessage(this.activeReceivedMessageId,null,DEL_CHAR);}}
if(messageSanitized.message.length){if(this.appendReceivedMessage){this.appendReceivedMessage=false;if(!this.view.classList.contains('display')){let message=navigator.mozL10n.get('new-message')+' '+this.name;CallScreen.showToast(null,null,message);}
console.log('RTT append new received message');this.activeReceivedMessageId=this.appendMessage({direction:'received',body:messageSanitized.message});}else{this.updateMessage(this.activeReceivedMessageId,null,messageSanitized.message);}}};RttView.prototype.sendMessage=function rv_sendMessage(message){console.log('RTT sendMessage '+message);if(message===SEND_CHAR){this.call.sendRttMessage(SEND_CHAR);return;}
if((message.length===2)&&(message.charCodeAt(0)>=55296)){this.call.sendRttMessage(message);return;}
let i;let diffIndex=message.length;for(i=0;i<message.length;i++){if(message[i]!==this.backupMsg[i]){diffIndex=i;break;}}
for(i;i<this.backupMsg.length;i++){console.log('RTT send DEL_CHAR');this.call.sendRttMessage(DEL_CHAR);}
for(i=diffIndex;i<message.length;i++){console.log('RTT sendRttMessage '+message.substring(i,i+1));this.call.sendRttMessage(message.substring(i,i+1));}
this.backupMessage(message);};RttView.prototype.backupMessage=function rv_backupMessage(inputMessage){this.backupMsg=inputMessage;console.log('RTT backupMessage '+this.backupMsg);};RttView.prototype.resetInput=function rtt_resetInput(){this.appendSentMessage=true;this.messageInput.value='';this.backupMessage(this.messageInput.value);if(this.inputTime){clearTimeout(this.inputTime);this.inputTime=null;}};RttView.prototype.resetReceive=function rtt_resetReceive(){this.appendReceivedMessage=true;if(this.receiveTime){clearTimeout(this.receiveTime);this.receiveTime=null;}};RttView.prototype.sanitizedMessage=function rtt_sanitizedMessage(mes){let message=mes;let messageSanitized={del:'',message:''};var length=(message.split(DEL_CHAR)).length-1;if(length===0){messageSanitized.message=message;}else if(length===message.length){messageSanitized.del=message;}else{let fromindex=1;for(let i=1;i<=length;i++){let index=message.indexOf(DEL_CHAR,fromindex);if(index!==-1&&message[index-1]!==DEL_CHAR){message=message.substring(0,index-1)+
message.substring(index+1,message.length);}else{fromindex++;}}
let newLength=message.split(DEL_CHAR).length-1;messageSanitized.del=message.substring(0,newLength);messageSanitized.message=message.substring(newLength);}
return messageSanitized;};RttView.prototype.handleInput=function rv_handleInput(evt){switch(evt.key){case'ArrowUp':window.setTimeout(()=>{let messageInput=this.messageInput;let length=messageInput.value.length;messageInput.setSelectionRange(length,length);});case'ArrowDown':let detail={curRttView:this.view,key:evt.key};window.dispatchEvent(new CustomEvent('rttViewChange',{detail:detail}));evt.stopPropagation();evt.preventDefault();break;case'Backspace':if(this.showLastSentMessageTimer){return;}
this.showLastSentMessageTimer=setTimeout(()=>{this.showLastSentMessageTimer=null;this.showLastSentMessage();},200);break;case'ArrowLeft':case'ArrowRight':evt.stopPropagation();evt.preventDefault();break;}};RttView.prototype.appendMessage=function rv_appendMessage(message){let messageId;let lastMessage=RttCache.getMessage(this.callId,this.nextMesageId-1);if(lastMessage&&lastMessage.direction==='sent'&&!lastMessage.body){messageId=this.nextMesageId-1;}else{messageId=this.nextMesageId++;}
console.log('RTT appendMessage '+messageId);RttCache.setMessage(this.callId,messageId,message);return messageId;};RttView.prototype.updateMessage=function rv_updateMessage(messageId,body,receiveMessage){console.log('RTT updateMessage '+messageId);let message=RttCache.getMessage(this.callId,messageId);if(body!==null){message.body=body;}else{if(receiveMessage===DEL_CHAR){console.log('RTT receive DEL_CHAR');message.body=message.body.substring(0,message.body.length-1);}else{message.body+=receiveMessage;}}
RttCache.setMessage(this.callId,messageId,message);};RttView.prototype.showLastSentMessage=function showLastSentMessage(){if(!this.messageInput.value){let message=RttCache.getLastMessage(this.callId,'sent');if(message&&message.id!==undefined){this.messageInput.value=message.body;this.activeSentMessageId=message.id;this.appendSentMessage=false;this.backupMessage(message.body);console.log('RTT last message id for set is '+this.activeSentMessageId);let messageInput=this.messageInput;let length=messageInput.value.length;messageInput.setSelectionRange(length,length);}}};