'use strict';var DownloadManager=(function(){var mozDownloadManager=navigator.mozDownloadManager;if(!mozDownloadManager){console.error('navigator.mozDownloadManager not supported!');return;}
mozDownloadManager.clearAllDone();var started=false;function onDownloadStart(ev){if(started){createDownloadNotification(ev.download);}else{LazyLoader.load(['shared/js/download/download_formatter.js','shared/js/download/download_ui.js','shared/js/download/download_store.js','shared/js/download/download_helper.js','js/download/download_notification_store.js','js/download/download_handler.js','js/download/download_notification.js'],function(){started=true;createDownloadNotification(ev.download);window.addEventListener('will-shutdown',function onShutdown(){ev.download.pause();});});}}
function openDownload(message){const path=message.tag;const filename=message.title;let request=DownloadStore.getAll();request.onsuccess=function(event){const completedDownloads=event.target.result;let download={}
if(completedDownloads.find){download=completedDownloads.find((downloadItem)=>{return downloadItem.path===path;});}else if(completedDownloads&&completedDownloads.path===path){download=completedDownloads;}
if(download){DownloadHandler.handlerOpenDownload({download,filename});}
if(!download){DownloadHandler.fileNotFoundDialog(filename);}};request.onerror=function(){console.warn('Download DATASTORE FAILED');};}
function handleSystemMessageNotification(message){openDownload(message);closeSystemMessageNotification(message);}
function closeSystemMessageNotification(msg){Notification.get({tag:msg.tag}).then(notifs=>{notifs.forEach(notif=>{if(notif.tag){if(notif.tag===msg.tag){notif.close&&notif.close();}}else{if(notif.body===msg.body){notif.close&&notif.close();}}});});}
function initNotificationHandler(){Service.request('handleSystemMessageNotification','system-download',{handleSystemMessageNotification,});}
function init(){window.removeEventListener('logohidden',init);initNotificationHandler();if(!started){LazyLoader.load(['shared/js/download/download_formatter.js','shared/js/download/download_ui.js','shared/js/download/download_store.js','shared/js/download/download_helper.js','js/download/download_notification_store.js','js/download/download_handler.js','js/download/download_notification.js'],function(){started=true;});}}
window.addEventListener('logohidden',init);mozDownloadManager.addEventListener('downloadstart',onDownloadStart);function createDownloadNotification(download){if(download.state==='started'||download.state==='downloading'||!DownloadNotificationStore.isDeletedNotification(download.path)){return new DownloadNotification(download);}
return null;}}());