
(function(exp){'use strict';var CallScreen={_screenWakeLock:null,_screenWakeLockCount:0,_hasVolumeKey:true,_hasEndCallKey:true,_hasCameraKey:false,_supportVT:false,_isParentalControl:false,_memOnDevice:null,_isAdjustingVolume:false,_volumeTimer:null,_activity:null,_wfcAlertTone:null,_wfcDialogTime:0,_dialog:null,_:navigator.mozL10n.get,_arrowLeftKeyDown:false,_minWfcRemindInterval:10000,_qwertyKeyMapping:{'w':'1','e':'2','r':'3','s':'4','d':'5','f':'6','z':'7','x':'8','c':'9',',':'0','o':'+','a':'*','q':'#'},callEndPromptTime:2000,callNodeHideTime:2100,body:document.body,screen:document.getElementById('call-screen'),calls:document.getElementById('calls'),blobURL:null,contactBackground:document.getElementById('contact-background'),bluetoothMenu:document.getElementById('bluetooth-menu'),switchToDeviceButton:document.getElementById('btmenu-btdevice'),switchToReceiverButton:document.getElementById('btmenu-receiver'),switchToSpeakerButton:document.getElementById('btmenu-speaker'),replyMenu:document.getElementById('reply-menu'),incomingContainer:document.getElementById('incoming-container'),incomingInfo:document.getElementById('incoming-info'),incomingNumber:document.getElementById('incoming-number'),incomingNumberAdditionalTel:document.getElementById('incoming-number-additional-info-tel'),incomingNumberAdditionalTelType:document.getElementById('incoming-number-additional-info-tel-type'),incomingHdIcon:document.getElementById('incoming-container').querySelector('.hd-icon'),incomingStirChecked:document.getElementById('incoming-container').querySelector('.stir-checked'),dialNumberOuterNode:document.getElementById('dialing-info'),dialNumberNode:document.querySelector('#dialing-number bdi'),translateKey:function(key){return this._qwertyKeyMapping[key]||key;},debug:function(message){console.log('Callscreen App: '+message);},updateCallScreenMode:function cs_updatecCallScreenMode(mode){this.calls.setAttribute('show-mode',mode);},updateCallsDisplay:function cs_updateCallsDisplay(){CallScreenHelper.render();var visibleCalls=this.calls.querySelectorAll('section:not([hidden])').length-1;this.body.classList.toggle('single-line',visibleCalls<=1);this.calls.classList.toggle('big-duration',visibleCalls<=1);},updateHeldDisplay:function cs_updateHeldDisplay(){const callHeld=this.calls.querySelector('.isHeld');if(callHeld){const mode=this.calls.getAttribute('show-mode');const duration=callHeld.dataset.duration;const childNode=callHeld.querySelector('span');if(mode==='max-mode'){Utils.prettyDuration(childNode,+duration,'callHeldDuration');}else{childNode.textContent=this._('hold');}}},updateCallsMuteState:function cs_updateCallsMuteState(){this.calls.classList.toggle('mute',CallsHandler.isMute);},hideDtmfNumber:function cs_hideDtmfNumber(){if(this.dialNumberOuterNode.style.display==='block'){this.dialNumberNode.textContent='';DtmfHelper.dtmfNumber='';this.dialNumberOuterNode.style.display='';}
CallScreenHelper.render();},showDtmfNumber:function cs_showDtmfNumber(phoneNumber){if(!CallsHandler.canShowDtmfScreen){DtmfHelper.dtmfNumber='';return;}
if(phoneNumber.length){this.dialNumberNode.textContent=phoneNumber;this.dialNumberOuterNode.style.display='block';CallScreenHelper.showDtmfScreenOption();FontSizeManager.adaptToSpace(FontSizeManager.SINGLE_CALL,this.dialNumberNode,false,'begin');}else{this.hideDtmfNumber();}},isDtmfNumberShown:function cs_isDtmfNumberShown(){if(DtmfHelper.dtmfNumber!=''){return true;}else{return false;}},keydownHandler:function cs_keydownHandler(evt){if(Rtt.isRttViewShown()){return;}
let key=this.translateKey(evt.key);switch(key){case'1':case'2':case'3':case'4':case'5':case'6':case'7':case'8':case'9':case'0':if(!CallsHandler.isShowInfo){CallsHandler.toggleShowInfo();CallsHandler.handleCallInfoTimer(true);evt.preventDefault();evt.stopPropagation();}
case'#':case'*':if(OptionHelper.softkeyPanel&&OptionHelper.softkeyPanel.menuVisible){OptionHelper.softkeyPanel.hideMenu();}
break;case'Call':var callsElement=document.getElementById('calls');if(CallScreenHelper.getCall('incoming')){CallsHandler.answer();}else if(callsElement.getAttribute('show-mode')==='list-mode'&&!DialerHelper.isDialerHelperShown()){CallsHandler.toggleCalls();}
break;case'EndCall':if(CallScreen.bluetoothMenu.classList.contains('display')){CallScreen.toggleBluetoothMenu(false);}
if(CallScreen.isDtmfNumberShown()){CallScreen.hideDtmfNumber();}
CallsHandler.end();break;case'BrowserBack':case'Backspace':if(CallScreen.bluetoothMenu.classList.contains('display')){CallScreen.toggleBluetoothMenu(false);}else if(this.replyMenu.classList.contains('display')){CallScreen.toggleReplyMenu(false);}else if(ConferenceGroupUI.isGroupDetailsShown()){ConferenceGroupUI.hideGroupDetails();}else if(!NavigationMap.menuIsActive&&!CallScreen._isAdjustingVolume){if(CallScreen._hasEndCallKey&&DialerHelper.isDialerHelperShown()){return;}
if(CallScreen.isDtmfNumberShown()){CallScreen.hideDtmfNumber();}
if(!CallScreen._hasEndCallKey){CallsHandler.end();}}
evt.preventDefault();evt.stopPropagation();break;case'SoftRight':break;case'SoftLeft':break;case'ArrowUp':var optionMenu=document.querySelector('#option-menu');if(optionMenu&&!optionMenu.classList.contains('visible')){evt.preventDefault();evt.stopPropagation();}
CallScreen.requestVolume('up');break;case'ArrowDown':var optionMenu=document.querySelector('#option-menu');if(optionMenu&&!optionMenu.classList.contains('visible')){evt.preventDefault();evt.stopPropagation();}
CallScreen.requestVolume('down');break;case'ArrowRight':if(!DialerHelper.isDialerHelperShown()&&(OptionHelper.getLastParamName()==='inCallTwoLinesParams'||OptionHelper.getLastParamName()==='inCallEndAndAnswerParams')){DialerHelper.showDialerHelper();CallScreenHelper.showDailerHelperCommandModeOption();}
break;case'ArrowLeft':if(!DialerHelper.isDialerHelperShown()&&!this._arrowLeftKeyDown){this._arrowLeftKeyDown=true;if(!this._hasCameraKey){CallRecording.manualCallRec();}}
break;case'Camera':CallRecording.manualCallRec();break;case'HeadsetHook':if(CallScreenHelper.getCall('incoming')){CallsHandler.answer();}else{CallsHandler.end();}
break;default:return;}},keyupHandler:function cs_keyupHandler(evt){switch(evt.key){case'Camera':evt.preventDefault();break;case'ArrowLeft':this._arrowLeftKeyDown=false;break;default:break;}},init:function cs_init(){window.addEventListener('keydown',this.keydownHandler.bind(this),true);window.addEventListener('keyup',this.keyupHandler.bind(this));navigator.hasFeature('device.capability.volume-key').then((hasVolumeKey)=>{this._hasVolumeKey=!!hasVolumeKey;});navigator.hasFeature('device.capability.endcall-key').then((hasEndCallKey)=>{this._hasEndCallKey=!!hasEndCallKey;});navigator.hasFeature('device.capability.camera-key').then((hasCameraKey)=>{this._hasCameraKey=!!hasCameraKey;});navigator.hasFeature('device.capability.vilte').then((supportVT)=>{this._supportVT=!!supportVT;});navigator.hasFeature('device.capability.parental-control').then((isPc)=>{this._isParentalControl=!!isPc;});navigator.getFeature('hardware.memory').then((memOnDevice)=>{this._memOnDevice=memOnDevice;});this.switchToDeviceButton.click=()=>{this.switchToDefaultOut(false);this.showToast('switch-to-device-toast');};this.switchToReceiverButton.click=()=>{CallsHandler.enableSpeaker=false;this.switchToReceiver();this.showToast('switch-to-handset-toast');};this.switchToSpeakerButton.click=()=>{CallsHandler.enableSpeaker=true;this.switchToSpeaker();this.showToast('switch-to-speaker-toast');};if(this.isMultiSIM()){var conns=navigator.mozMobileConnections;for(let cardIndex=0;cardIndex<conns.length;cardIndex++){const conn=conns[cardIndex];if(conn&&conn.imsHandler){conn.imsHandler.addEventListener('capabilitychange',this.updateCapability.bind(this));}}}},showToast:function cs_showToast(L10nId,title,message){var toast={messageL10nId:L10nId,message:message?message:null,useTransition:true};if(title){toast.title=title;}
Toaster.showToast(toast);},setCallerContactImage:function cs_setCallerContactImage(){var activeCallForContactImage=CallsHandler.activeCallForContactImage;var blob=activeCallForContactImage&&activeCallForContactImage.photo;if(this.blobURL){URL.revokeObjectURL(this.blobURL);this.blobURL=null;}
PhotoResize.resize(blob).then(resizeBlob=>{this.blobURL=URL.createObjectURL(resizeBlob);this.contactBackground.style.backgroundImage='url('+this.blobURL+')';});},insertCall:function cs_insertCall(node){if(typeof CallScreenHelper!='undefined'){CallScreenHelper.render();var template=document.getElementById('handled-call-template');this.calls.insertBefore(node,template);this.updateCallsDisplay();}
this.updateCapability();},removeCall:function cs_removeCall(node){CallScreenHelper.render();if(node.parentNode){node.parentNode.removeChild(node);this.updateCallsDisplay();}},launchMore:function cs_lanchMore(){var activity=new MozActivity({name:'pick',data:{type:['webcontacts/tel','calllog/tel']}});this._activity=activity;activity.onsuccess=()=>{if(activity.result&&activity.result.tel&&activity.result.tel[0]&&activity.result.tel[0].value){CallsHandler.dial(activity.result.tel[0].value);DialerHelper.hideDialerHelper();}else{DialerHelper.focus();}
this._activity=null;CallsHandler.enableScreenDimFeature(true);};activity.onerror=()=>{this._activity=null;CallsHandler.enableScreenDimFeature(true);DialerHelper.focus();};CallsHandler.enableScreenDimFeature(false);},cancelActivity:function cs_cancelActivity(){if(this._activity){this._activity.cancel();this._activity=null;}},launchMessages:function cs_launchMessages(){const activity=new window.MozActivity({name:'latest-message'});this._activity=activity;},toggleBluetoothMenu:function cs_toggleBluetoothMenu(value){if(typeof value!='boolean'){this.bluetoothMenu.classList.toggle('display');}else{this.bluetoothMenu.classList.toggle('display',value);}
if(this.bluetoothMenu.classList.contains('display')){CallScreenHelper.showMenuDialogOptions();var navId=0;if(CallsHandler.isBtConnected){this.switchToDeviceButton.classList.toggle('selected',true);}else if(window.navigator.mozTelephony.speakerEnabled===false){this.switchToReceiverButton.classList.toggle('selected',true);navId=1;}else if(window.navigator.mozTelephony.speakerEnabled===true){this.switchToSpeakerButton.classList.toggle('selected',true);navId=2;}
NavigationManager.reset('#bluetooth-menu .option-item',navId);}else{var groupCalls=document.getElementById('group-call-details');var dialerHelper=document.getElementById('dialer-helper');if(groupCalls&&groupCalls.classList.contains('display')||dialerHelper&&dialerHelper.classList.contains('display')||this._activity){return;}
if(document.activeElement.classList.contains('option-item')){document.activeElement.blur();}
if(Rtt.isRttViewShown()){this.showRttView();}else{CallScreenHelper.render();}
this.switchToDeviceButton.classList.toggle('selected',false);this.switchToReceiverButton.classList.toggle('selected',false);this.switchToSpeakerButton.classList.toggle('selected',false);}},toggleReplyMenu:function cs_toggleReplyMenu(value){this.replyMenu.classList.toggle('display',value);if(value){CallScreenHelper.showMenuDialogOptions();NavigationManager.reset('#reply-menu .option-item',0);}else{if(document.activeElement.classList.contains('option-item')){document.activeElement.blur();}
CallScreenHelper.render();}},replyItemSelected:function cs_replyItemSelected(){let focusItem=this.replyMenu.querySelector('.focus');if(!focusItem){return;}
let number=CallsHandler.incomingCall.call.id.number;if(focusItem.id&&focusItem.id==='reply-custom'){setTimeout(()=>{const activity=new window.MozActivity({name:'new',data:{type:'websms/sms',number:number,from:'callscreen'}});},this.callEndPromptTime);}else{CallsHandler.replyMessage(focusItem.textContent);}
CallsHandler.end();},isBtMenuDisplayed:function cs_isBtMenuDisplayed(){return this.bluetoothMenu.classList.contains('display');},switchToSpeaker:function cs_switchToReceiver(){CallsHandler.switchToSpeaker();this.toggleBluetoothMenu(false);},switchToReceiver:function cs_switchToReceiver(){CallsHandler.switchToReceiver();this.toggleBluetoothMenu(false);},switchToDefaultOut:function cs_switchToDefaultOut(doNotConnect){CallsHandler.switchToDefaultOut(doNotConnect);this.toggleBluetoothMenu(false);},setBTReceiverIcon:function cs_setBTReceiverIcon(enabled){if(OptionHelper.getLastParamName()){OptionHelper.swapParams(OptionHelper.getLastParamName());if(!enabled){this.toggleBluetoothMenu(false);}}},placeNewCall:function cs_placeNewCall(){DialerHelper.showDialerHelper();CallScreenHelper.showDailerHelperOption();},showIncoming:function cs_showIncoming(){this.body.classList.remove('showKeypad');this.incomingContainer.classList.add('displayed');var items=document.querySelectorAll('.handled-call');for(var i=0;i<items.length;i++){items[i].classList.add('fadeout');}
CallScreenHelper.render();this.lockScreenWake();},hideIncoming:function cs_hideIncoming(){this.incomingContainer.classList.remove('displayed');var items=document.querySelectorAll('.handled-call');for(var i=0;i<items.length;i++){items[i].classList.remove('fadeout');}
CallScreenHelper.render();this.unlockScreenWake();},incomingEnded:function cs_incomingEnded(){this.incomingInfo.classList.add('ended');this.incomingNumberAdditionalTelType.textContent='';this.incomingNumberAdditionalTel.textContent=this._('callEnded');setTimeout(()=>{this.hideIncoming();},this.callEndPromptTime);},handleCallWaitingScreen:function(){var show=false;var displayed=this.incomingContainer.classList.contains('displayed');if(displayed&&this.calls.getAttribute('show-mode')==='list-mode'){show=true;}
CallScreen.showListModeCallWaiting(show);},showListModeCallWaiting:function(show){if(show){this.screen.classList.add('list-mode-call-waiting');}else{this.screen.classList.remove('list-mode-call-waiting');}},lockScreenWake:function cs_lockScreenWake(){this._screenWakeLockCount++;if(!this._screenWakeLock){this._screenWakeLock=navigator.requestWakeLock('screen');}},unlockScreenWake:function cs_unlockScreenWake(){if(this._screenWakeLockCount){this._screenWakeLockCount--;}
if(this._screenWakeLock&&!this._screenWakeLockCount){this._screenWakeLock.unlock();this._screenWakeLock=null;}},rendVoWifiQuality:function(parentNode,display){var qualityContainerNode=parentNode.querySelector('.wifi-call-quality-container');var active=CallScreenHelper.telephony.active;var vowifiQuality=active&&active.vowifiQuality;if(vowifiQuality===undefined){vowifiQuality=active&&active.calls&&active.calls[0]&&active.calls[0].vowifiQuality;}
if(display&&vowifiQuality&&vowifiQuality!=='none'){parentNode.classList.add('wifi-call');var contentNode=qualityContainerNode.querySelector('.quality-content');var dotNode=qualityContainerNode.querySelector('.quality-dot');contentNode.setAttribute('data-l10n-id','wifi-call-quality-'+vowifiQuality);dotNode.setAttribute('data-quality',vowifiQuality);qualityContainerNode.classList.remove('hide');}else{qualityContainerNode.classList.add('hide');parentNode.classList.remove('wifi-call');}},showRecIndicator:function(parentNode,display){var recContainerNodes=parentNode.querySelectorAll('.call-recording-container');var i=0;if(display){parentNode.classList.add('show-rec');for(i=0;i<recContainerNodes.length;i++){recContainerNodes[i].classList.remove('hide');}}else{parentNode.classList.remove('show-rec');for(i=0;i<recContainerNodes.length;i++){recContainerNodes[i].classList.add('hide');}}},createTicker:function(durationNode,groupPassTime){var durationChildNode=durationNode.querySelector('span');if(durationNode.dataset.tickerId){return false;}
durationNode.classList.add('isTimer');if(groupPassTime===undefined){groupPassTime=Date.now();}
durationNode.dataset.startTime=groupPassTime;var delta=Math.round((Date.now()-groupPassTime)/1000)*1000;Utils.prettyDuration(durationChildNode,delta);var ticker=setInterval(()=>{var delta=Math.round((Date.now()-groupPassTime)/1000)*1000;durationNode.dataset.duration=delta;if(durationNode.classList.contains('isHeld')){if(this.getNodeNum()===1){Utils.prettyDuration(durationChildNode,delta,'callHeldDuration');}else{durationChildNode.textContent=this._('hold');}}else{Utils.prettyDuration(durationChildNode,delta);}
var listCallNode=durationNode.parentNode;CallScreen.rendVoWifiQuality(listCallNode,typeof delta!=='undefined');},1000,Date.now());durationNode.dataset.tickerId=ticker;return true;},stopTicker:function(durationNode){durationNode.classList.remove('isTimer');clearInterval(durationNode.dataset.tickerId);delete durationNode.dataset.tickerId;delete durationNode.dataset.startTime;delete durationNode.dataset.duration;},requestVolume:function cs_requestVolume(option){if(!CallScreen.isVolumeRequestNeeded(option)){return;}
if(navigator.volumeManager){switch(option){case'up':navigator.volumeManager.requestUp();break;case'down':navigator.volumeManager.requestDown();break;case'show':navigator.volumeManager.requestShow();break;default:return;}
this._isAdjustingVolume=true;clearTimeout(this._volumeTimer);this._volumeTimer=setTimeout(()=>{this._isAdjustingVolume=false;},2000);}},isVolumeRequestNeeded:function cs_isVolumeRequestNeeded(option){if(this._hasVolumeKey||CallScreen.bluetoothMenu.classList.contains('display')||CallScreen.replyMenu.classList.contains('display')||ConferenceGroupUI.isGroupDetailsShown()||(NavigationMap.menuIsActive&&option!=='show')||this.isConfirmDialogShown()||(CallsHandler.openLines()===1&&CallScreenHelper.getCall('incoming'))){return false;}else{return true;}},showMainCallscreen:function cs_showMainCallscreen(){if(DialerHelper.isDialerHelperShown()){DialerHelper.hideDialerHelper();}
if(LockScreen.isLockScreenShown()){LockScreen.showLockScreen(false);}
if(this.isConfirmDialogShown()){this.closeConfirmDialog();this._wfcDialogTime=new Date();}
if(this.isDtmfNumberShown()){this.hideDtmfNumber();}
if(OptionHelper.softkeyPanel&&OptionHelper.softkeyPanel.menuVisible){OptionHelper.softkeyPanel.hideMenu();}
if(this.bluetoothMenu.classList.contains('display')){this.toggleBluetoothMenu(false);}
if(this.replyMenu.classList.contains('display')){this.toggleReplyMenu(false);}
if(ConferenceGroupUI.isGroupDetailsShown()){ConferenceGroupUI.hideGroupDetails();}
this.cancelActivity();Rtt.hideRttView();},isEndCallKeyExisted:function cs_isEndKeyExisted(){return this._hasEndCallKey;},supportVT:function cs_supportVT(){return this._supportVT;},isParentalControl:function cs_isParentalControl(){return this._isParentalControl;},memOnDevice:function cs_memOnDevice(){return this._memOnDevice;},remindBadWfc:function cs_remindBadWfc(){if(!this._wfcAlertTone){this._wfcAlertTone=true;TonePlayer.playSequence([[480,620,250]]);}
if(this.isConfirmDialogShown()){return;}
let currentTime=new Date();if(currentTime-this._wfcDialogTime>=this._minWfcRemindInterval){let message=this._('wifi-calling-1')+' '+this._('wifi-calling-2');let dialogConfig={title:{id:'wifi-calling',args:{}},body:{text:message},accept:{name:'ok',l10nId:'ok',priority:2,callback:function(){CallScreen._wfcDialogTime=new Date();}}};this.showConfirmDialog(dialogConfig);}},showConfirmDialog:function cs_showConfirmDialog(dialogConfig){this.closeConfirmDialog();if(this._activity&&DialerHelper.isDialerHelperShown()){DialerHelper.hideDialerHelper();}
this._dialog=new ConfirmDialogHelper(dialogConfig);this._dialog.show(document.getElementById('vt-confirmation-dialog'));},closeConfirmDialog:function cs_closeConfirmDialog(){if(this._dialog){this._dialog.close();}
this._dialog=null;},isConfirmDialogShown:function cs_isConfirmDialogShown(){return this._dialog&&this._dialog.isShown;},resetWfcRemind:function cs_resetWfcAlert(){this._wfcAlertTone=false;this._wfcDialogTime=0;},getScenario:function cs_getScenario(){var scenario;if(this.body.classList.contains('single-line')){scenario=FontSizeManager.SINGLE_CALL;}else{scenario=FontSizeManager.CALL_WAITING;}
return scenario;},handleCallError:function cs_handleCallError(errorName,number){var title='';var message='';if(errorName==='BadNumber'){title='invalidNumberToDialTitle';message='invalidNumberToDialMessage';}else if(errorName==='FDNBlockedError'||errorName==='FdnCheckFailure'){title='fdnIsActiveTitle';message='fdnIsActiveMessage';}else if(errorName==='NumberBlocked'){message='numberBlockedMessage';}else{return;}
let dialogConfig={title:{id:title,args:{}},body:{id:message,args:{number:number}},accept:{name:'ok',l10nId:'ok',priority:2,callback:function(){CallScreen._wfcDialogTime=new Date();}}};this.showConfirmDialog(dialogConfig);},showRttView:function cs_showRttView(){Rtt.showRttView();CallScreenHelper.showRttViewOption();},isMultiSIM:function cs_isMultiSIM(){if(navigator.mozIccManager&&navigator.mozIccManager.iccIds.length>1){return true;}
return false;},getSimNum:function cs_getSimNum(call){let simNum='';if(call&&typeof call.serviceId!=='undefined'&&this.isMultiSIM()){simNum=`-sim${parseInt(call.serviceId) + 1}`;}
return simNum;},updateCapability:function cs_updateCapability(){if(!this.isMultiSIM()){return;}
let ims='';const imsHandler=navigator.mozMobileConnections[CallsHandler.serviceId].imsHandler;if(imsHandler){if((imsHandler.capability==='voice-over-wifi'||imsHandler.capability==='video-over-wifi')&&(!imsHandler.unregisteredReason)){ims='vowifi';}else if((imsHandler.capability==='voice-over-cellular'||imsHandler.capability==='video-over-cellular')&&(!imsHandler.unregisteredReason)){ims='volte';}}
if(ims){ims=`call-${ims}-sim${parseInt(CallsHandler.serviceId) + 1}`;}
const statusIcons=document.querySelectorAll('.status-icon');for(let i=0;i<statusIcons.length;i++){const statusIcon=statusIcons[i];if(ims){statusIcon.dataset.ims=ims;}else{statusIcon.classList.remove('ims');delete statusIcon.dataset.ims;}}},getNodeNum:function cs_getNodeNum(){if(this.calls.getAttribute('show-mode')==='max-mode'){return 1;}else{return document.querySelectorAll('.handled-call:not([hidden])').length+
!document.getElementById('group-call').hidden;}}};exp.CallScreen=CallScreen;}(window));