
(function(exports){'use strict';var resources=['/shared/js/component_utils.js','/shared/elements/gaia_confirm/script.js'];var dialogHelperElement=null;var confirmSoftkey=null;function ConfirmDialogHelper(config){this.config=config;this.isPrompt=config.type&&config.type==='prompt';}
ConfirmDialogHelper.prototype={activeElement:null,deltaTop:100,Softkey:confirmSoftkey,isShown:false,show:function(parent){LazyLoader.load(resources,this._show.bind(this,parent));},_show:function(parent){var config=this.config;var self=this;self.parent=parent;self.activeElement=document.activeElement;var wrapper=document.createElement('div');var cancelButton=config.cancel?'<button class="cancel" type="button"></button>':'';var confirmClass=config.system?"insystem":"";var inputLabel=this.isPrompt?'<p class="confirm-input-container"><input></p>':'';var contentClass=config.otherClass?config.otherClass+' content':'content';wrapper.innerHTML='<gaia-confirm role="menuitem" tabindex="-1" class='+confirmClass+'>'+'<h1 style="text-align:center;"></h1>'+'<div class='+contentClass+'><div>'+'<p class="confirm-body"></p>'+'<p class="noborder" hidden></p>'+
inputLabel+'</div></div>'+'</gaia-confirm>';var element=wrapper.firstElementChild;this.element=element;dialogHelperElement=element;element.dataset.type=config.type;element.addEventListener('confirm',this);element.addEventListener('cancel',this);element.addEventListener('accept',this);window.addEventListener('keydown',this);window.addEventListener('hashchange',this);var plist=element.querySelectorAll('p');var title=element.querySelector('h1');var body=plist[0];var desc=plist[1];var setL10nAttributes=function(element,options){if('string'===typeof options){navigator.mozL10n.setAttributes(element,options);}
if(options.id){navigator.mozL10n.setAttributes(element,options.id,options.args);}else if(options.text){element.textContent=options.text;}};setL10nAttributes(title,config.title);setL10nAttributes(body,config.body);if(!config.title.id&&!config.title.text){element.querySelector('h1').hidden=true;}
if(config.desc||(config.desc&&config.desc!=='')){desc.hidden=false;setL10nAttributes(desc,config.desc);}else{desc.hidden=true;}
if(NavigationMap&&NavigationMap.currentActivatedLength>-1){if(NavigationMap.currentActivatedLength==0){NavigationMap.currentActivatedLength=1;}else{setTimeout(function(){self.show(parent);},600);return;}}
element.setAttribute('hidden','');parent.appendChild(element);self.activeElement.blur();if(self.isPrompt){var inputDom=element.querySelector('input');for(var i=0;i<plist.length;i++){plist[i].classList.add('confirm-input-mode');}
element.addEventListener('transitionend',function _showend(){element.removeEventListener('transitionend',_showend);inputDom.focus();});}
window.requestAnimationFrame(()=>{window.requestAnimationFrame(()=>{element.removeAttribute('hidden');self.isShown=true;self.scrollContext('ArrowUp');window.dispatchEvent(new CustomEvent('gaia-confirm-open'));});});var softkeyParams={menuClassName:'menu-button',header:{},items:[]};if(config.cancel){softkeyParams.items.push({name:'',priority:1,l10nId:config.cancel.l10nId,method:function(){}});}
if(config.accept){softkeyParams.items.push({name:'',priority:2,l10nId:config.accept.l10nId,icon:config.accept.icon||null,method:function(){}});}
if(config.confirm){softkeyParams.items.push({name:'',priority:3,l10nId:config.confirm.l10nId,method:function(){}});}
if(!confirmSoftkey){confirmSoftkey=new SoftkeyPanel({menuClassName:'menu-button',items:[{name:'',priority:1,method:function(){console.log('confirmSoftkey created');}}]});}
confirmSoftkey.initSoftKeyPanel(softkeyParams);confirmSoftkey.show();},close:function(){this.destroy();confirmSoftkey&&confirmSoftkey.hide();},destroy:function(){if(!this.element){return;}
setTimeout(function(){if(NavigationMap&&NavigationMap.currentActivatedLength>-1){NavigationMap.currentActivatedLength=0;}},500);this.activeElement.focus();window.removeEventListener('hashchange',this);window.removeEventListener('keydown',this);this.element.addEventListener('transitionend',function removeAfterHide(e){if(e.target!==this.element){return;}
this.element.parentNode.removeChild(this.element);this.element=null;this.isShown=false;window.dispatchEvent(new CustomEvent('gaia-confirm-close'));}.bind(this));this.element.setAttribute('hidden','');},scrollContext:function(key){var dialogContainer=this.parent.querySelector('div.content');var dialogText=dialogContainer.querySelector('.confirm-body');var headerHeight=this.parent.querySelector('h1').clientHeight;var inputDom=this.parent.querySelector('.confirm-input-container');var inputHeight=inputDom?inputDom.clientHeight:0;var containerHeight=document.body.clientHeight-
this.getSoftkeyHeight()-this.getStatusBarHeight()-headerHeight;var padding=parseFloat(getComputedStyle(document.body).fontSize)*2;dialogText.style.maxHeight=containerHeight-inputHeight-padding+'px';if(dialogContainer.clientHeight<containerHeight){this.scroll=false;return;}
dialogText.scrollTop=key==='ArrowUp'?(dialogText.scrollTop-this.deltaTop):(dialogText.scrollTop+this.deltaTop);},getSoftkeyHeight:function(){var height=0;var softKeyPanel=document.querySelector('#'+FORM_ID);if(softkeyPanel&&softkeyPanel.classList.contains('visible'))
height=softkeyPanel.clientHeight;return height;},getStatusBarHeight:function(){var style=getComputedStyle(document.body);var fontSize=parseFloat(style.fontSize);var rem=parseFloat(style.getPropertyValue('--statusbar-height'))+2;return fontSize*rem;},handleEvent:function(e){switch(e.type){case'hashchange':break;case'confirm':this.destroy();var confirm=this.config.confirm.callback;if(confirm){if(this.isPrompt){confirm(this.element.querySelector('input').value);}else{confirm();}}
break;case'cancel':this.destroy();var cancel=this.config.cancel.callback;cancel&&cancel();break;case'accept':this.destroy();var accept=this.config.accept.callback;accept&&accept();break;}
switch(e.key){case"BrowserBack":case'Backspace':case"KanjiMode":case"Backspace":confirmSoftkey.hide();this.destroy();var back=this.config.backcallback;back&&back();e.preventDefault();e.stopPropagation();break;case"Enter":case"Accept":if(this.config.accept){confirmSoftkey.hide();this.element.dispatchEvent(new CustomEvent('accept'));}
break;case"ContextMenu":case"SoftLeft":case"F1":if(this.config.cancel&&this.isShown){confirmSoftkey.hide();this.element.dispatchEvent(new CustomEvent('cancel'));}
break;case"ArrowUp":case"ArrowDown":this.scrollContext(e.key);e.preventDefault();e.stopPropagation();break;case"BrowserSearch":case"SoftRight":case"F2":if(this.config.confirm&&this.isShown){confirmSoftkey.hide();this.element.dispatchEvent(new CustomEvent('confirm'));}
break;}}};window.ConfirmDialogHelper=ConfirmDialogHelper;}(window));