'use strict';var ConferenceGroupUI=(function(){var groupCalls=document.getElementById('group-call-details');var groupCallsList=document.getElementById('group-call-details-list');var groupLine=document.getElementById('group-call');var conNum=groupLine.querySelector('.numberWrapper .number bdi');var conInfo=groupLine.querySelector('.additionalContactInfo .tel-type');var groupDuration=document.querySelector('#group-call > .duration');var groupDurationChildNode=groupDuration.querySelector('span');var _=navigator.mozL10n.get;function updateGroupInformation(){var length=0;CallScreen.updateCallsDisplay();hideGroupDetails();if(isImsconferenceGroup()){var textContent=CallsHandler.getImsGroupDetailsText();if(textContent){conNum.textContent=textContent;length=textContent.split(',').length;}}else{conNum.textContent=CallsHandler.getGroupDetailsText();length=ConferenceGroupHandler.conferenceGroupLength;}
groupLine.classList.add('additionalInfo');conInfo.textContent=_('conference-call-num',{num:length});}
function show(simNum){groupLine.hidden=false;groupLine.classList.remove('ended');groupLine.classList.remove('held');groupLine.querySelector('.callended').classList.add('hidden');groupDuration.classList.remove('isHeld');var startTime=CallsHandler.getConferenceStartTime();CallScreen.createTicker(groupDuration,startTime);var statusIcon=groupLine.querySelector('.status-icon');if(simNum!==''){statusIcon.dataset.index=simNum;}else{delete statusIcon.dataset.index;}
CallScreen.updateCallsDisplay();CallScreen.rendVoWifiQuality(groupLine,true);const duration=groupDuration.dataset.duration;if(duration&&document.body.classList.contains('single-line')){Utils.prettyDuration(groupDurationChildNode,+duration);}}
function hold(){groupLine.classList.add('held');groupDuration.classList.add('isHeld');CallScreen.updateCallsDisplay();CallScreen.rendVoWifiQuality(groupLine,false);const duration=groupDuration.dataset.duration;if(duration&&document.body.classList.contains('single-line')){Utils.prettyDuration(groupDurationChildNode,+duration,'callHeldDuration');}}
function end(){if(document.body.classList.contains('single-line')){const duration=groupDuration.dataset.duration;if(duration){Utils.prettyDuration(groupDurationChildNode,+duration,'callEndedDuration');}else{groupDurationChildNode.textContent=_('callEnded');}}
groupLine.classList.add('ended');groupLine.classList.remove('held');groupLine.querySelector('.callended').classList.remove('hidden');CallScreen.stopTicker(groupDuration);CallScreen.showRecIndicator(groupLine,false);CallsHandler.clearConferenceStartTime();removeDetails();CallScreen.rendVoWifiQuality(groupLine,false);if(ConferenceGroupHandler.conferenceGroupLength===2){groupLine.hidden=true;CallScreen.updateCallsDisplay();return;}
var promptTime=CallsHandler.isAnyOpenCalls?CallScreen.callEndPromptTime:CallScreen.callNodeHideTime;setTimeout(function(){CallsHandler.conferenceCallEnd();groupLine.hidden=true;CallScreen.updateCallsDisplay();},promptTime);}
function hideGroupDetails(evt){if(evt){evt.preventDefault();}
if(!ConferenceGroupHandler.conferenceGroupLength){_removeAllCalls();}
groupCalls.classList.remove('display');CallScreenHelper.render();}
function _removeAllCalls(){var callNodes=groupCalls.querySelectorAll('.handled-call');for(var i=0;i<callNodes.length;i++){removeCall(callNodes[i]);}}
function createItem(info){var listItem=document.createElement('li');listItem.classList.add('conference_group_list');listItem.classList.add('p-pri');var infoItem=document.createElement('div');infoItem.textContent=info;listItem.appendChild(infoItem);return listItem;}
function addCall(info){var item=createItem(info);groupCallsList.appendChild(item);return item;}
function addImsCall(number,name){var item=createImsItem(number,name);groupCallsList.appendChild(item);return item;}
function createImsItem(number,name){var listItem=document.createElement('li');listItem.classList.add('conference_group_list');listItem.classList.add('p-pri');listItem.dataset.telenumber=number;var infoItem=document.createElement('div');if(name===''){infoItem.textContent=number;}else{infoItem.textContent=name;}
listItem.appendChild(infoItem);return listItem;}
function removeCall(node){groupCallsList.removeChild(node);}
function showGroupDetails(){NavigationManager.reset('.conference_group_list');groupCalls.classList.add('display');}
function removeDetails(){groupCallsList.innerHTML='';}
function endCall(){hideGroupDetails();var listItem=groupCalls.querySelector('.focus');if(listItem.endCall){listItem.endCall();}else{ConferenceGroupHandler.hangUpFromCallMap(listItem);}}
function isImsconferenceGroup(){if(CallsHandler.imsRegState!=='voice-over-cellular'&&CallsHandler.imsRegState!=='voice-over-wifi'&&CallsHandler.imsRegState!=='video-over-cellular'&&CallsHandler.imsRegState!=='video-over-wifi'){return false;}
var firstListItem=groupCallsList.childNodes[0];if(groupCallsList.childElementCount==0||firstListItem.endCall==undefined){return true;}else{return false;}}
function separateCall(){hideGroupDetails();var listItem=groupCalls.querySelector('.focus');if(listItem.separateCall){listItem.separateCall();}else{ConferenceGroupHandler.separateCallFromCallMap(listItem);}}
function isGroupDetailsShown(){return groupCalls.classList.contains('display');}
function markCallsAsEnded(){var callElems=groupCallsList.getElementsByTagName('li');for(var i=0;i<callElems.length;i++){callElems[i].dataset.groupHangup='groupHangup';}}
function showRecIndicator(display){CallScreen.showRecIndicator(groupLine,display);}
return{updateGroupInformation:updateGroupInformation,show:show,hold:hold,end:end,addCall:addCall,addImsCall:addImsCall,removeCall:removeCall,showGroupDetails:showGroupDetails,hideGroupDetails:hideGroupDetails,isGroupDetailsShown:isGroupDetailsShown,markCallsAsEnded:markCallsAsEnded,endCall:endCall,separateCall:separateCall,removeDetails:removeDetails,isImsconferenceGroup:isImsconferenceGroup,showRecIndicator:showRecIndicator,get currentDuration(){return groupDuration.dataset.duration;},get focusedItem(){return groupCalls.querySelector('.focus');}};})();