'use strict';function HandledCall(aCall){this.photo=null;this._leftGroup=false;this.call=aCall;this.allowedConnected=true;this.info='';this.blobURL=null;this.iccMessageBlobURL=null;this.outgoing=false;this._=navigator.mozL10n.get;this.rttViewAdded=false;this.rttMode='off';aCall.addEventListener('statechange',this);aCall.ongroupchange=()=>{if(this.call.group){this.item=ConferenceGroupHandler.addToGroupDetails(this.info);this.item.endCall=()=>{this.call.hangUp();};this.item.separateCall=()=>{window.navigator.mozTelephony.conferenceGroup.remove(this.call);};CallScreen.removeCall(this.node);this._leftGroup=false;}else if(this._wasUnmerged()){ConferenceGroupHandler.removeFromGroupDetails(this.item);CallScreen.insertCall(this.node);this._leftGroup=false;}else{ConferenceGroupHandler.removeFromGroupDetails(this.item);this._leftGroup=!this.item.dataset.groupHangup;}};if(CallScreen.supportVT()){var videoCallProvider=this.call.videoCallProvider;videoCallProvider.onsessionmodifyresponse=(resp)=>{VT.onsessionmodifyresponse(this.call,resp);};videoCallProvider.onsessionmodifyrequest=(req)=>{VT.onsessionmodifyrequest(this.call,req);};}
this.call.onrttmodifyresponse=(req)=>{Rtt.onrttmodifyresponse(this.call,req);};this.call.onrttmodifyrequest=(req)=>{Rtt.onrttmodifyrequest(this.call,req);};this._initialState=this.call.state;this._cachedInfo='';this._cachedAdditionalTel='';this._cachedAdditionalTelType='';this._removed=false;this._wasConnected=false;this.node=document.getElementById('handled-call-template').cloneNode(true);this.node.id='list-call';this.node.classList.add('handled-call');this.node.hidden=false;this.durationNode=this.node.querySelector('.duration');this.durationChildNode=this.node.querySelector('.duration span');this.numberNode=this.node.querySelector('.numberWrapper .number bdi');this.hdNode=this.node.querySelector('.hd-icon');this.outerNode=this.node.querySelector('.numberWrapper .number');this.photoItem=this.node.querySelector('.photo-icon');this.dialNumberNode=document.querySelector('#dialing-number bdi');this.dialNumberOuterNode=document.getElementById('dialing-number');this.additionalTelNode=this.node.querySelector('.additionalContactInfo .tel');this.additionalTelTypeNode=this.node.querySelector('.additionalContactInfo .tel-type');this.wifiCallQuality=this.node.querySelector('.quality-content');this.stirContainer=this.node.querySelector('.stir-container');this.stirChecked=this.node.querySelector('.additionalContactInfo .stir-checked');this.updateCallNumber();this.updateHdIcon();this.updateRttMode();var durationMessage;if(this.call.state==='incoming'){if(CallsHandler.isVideoCall()){durationMessage=this._('vt-incoming-call');}else{durationMessage=this._('kai-incoming-call');}
if(this.call.verStatus==='pass'){this.showStirIndicator(true);}}else{durationMessage=this._('connecting');}
this.durationChildNode.textContent=durationMessage;this.updateDirection();this.updateRttMode();if(this._initialState==='connected'||this._initialState==='held'){this.connected();}
if(this._initialState==='held'){this.node.classList.add('held');this.held();}
if(this.call.emergency&&(this.call.state==='dialing'||this.call.state==='alerting'||this.call.state==='connected')){AML.sendAMLSms(this.call.serviceId,this.call.id.number);}}
HandledCall.prototype._wasUnmerged=function hc_wasUnmerged(){return!this.node.dataset.groupHangup&&this.call.state!='disconnecting'&&this.call.state!='disconnected';};HandledCall.prototype.allowConnected=function hc_allowConnected(){if(!this.allowedConnected){this.allowedConnected=true;this.connected();}};HandledCall.prototype.handleEvent=function hc_handle(evt){CallScreenHelper.render();if(this.call.vowifiQuality==='bad'){CallScreen.remindBadWfc();}
this.updateHdIcon();this.updateRttMode();switch(evt.call.state){case'connected':if(!DialerHelper.isDialerHelperShown()){DtmfHelper.enableDtmf();}
if(this.allowedConnected){this.connected();}
CallRecording.autoCallRec();CallsHandler.initMicMode();break;case'disconnected':this.disconnected();console.log('disconnected');break;case'held':this.node.classList.add('held');this.held();break;}};HandledCall.prototype.updateHdIcon=function hc_updateHdIcon(){var infoContainerEl=this.node.querySelector('.infoContainer');if(this.call.voiceQuality==='Normal'){infoContainerEl.setAttribute('hdicon-display','hide');}else{infoContainerEl.setAttribute('hdicon-display','show');}
this.hdNode.classList.toggle('hide',this.call.voiceQuality==='Normal');};HandledCall.prototype.updateCallNumber=function hc_updateCallNumber(){var number=this.call.id.number;var node=this.numberNode;var self=this;if(this.call.secondId){node.textContent=this._('switch-calls');this._cachedInfo=this._('switch-calls');this._cachedAdditionalTel='';this._cachedAdditionalTelType='';this.replaceAdditionalContactInfo('','');this.numberNode.style.fontSize='';return;}
if(!number){this.info=this._('unknown');node.textContent=this.info;this._cachedInfo=this.info;return;}
var isEmergencyNumber=this.call.emergency;if(isEmergencyNumber){this.node.classList.add('emergency');this.photoItem.setAttribute('data-icon','call-emergency-32');this.photoItem.setAttribute('dir','ltr');node.textContent=number;this._cachedInfo=number;this.replaceAdditionalContactInfo(this._('emergencyNumber'),'');this._cachedAdditionalTel=this._('emergencyNumber');this._cachedAdditionalTelType='';return;}
var isVoicemailNumber=Voicemail.check(number,this.call.serviceId);if(isVoicemailNumber){this.node.classList.add('voice-mail');this.photoItem.setAttribute('data-icon','voicemail-32');this.photoItem.setAttribute('dir','ltr');node.textContent=this._('voiceMail');this._cachedInfo=this._('voiceMail');this.info=this._('voiceMail');CallsHandler.insertImsRecord(number,this.info);}else{const sdnContacts=SdnContacts.get();const contacts=sdnContacts[this.call.serviceId];if(contacts&&contacts.get(number)){this.info=contacts.get(number);this._cachedInfo=this.info;node.textContent=this.info;this.replaceAdditionalContactInfo(number,'');this.formatPhoneNumber('end');CallsHandler.insertImsRecord(number,this.info);return;}
this.photoItem.setAttribute('dir','auto');if(this.call.state!=='connected'){lookupContact(undefined);}
Contacts.findByNumber(number,lookupContact);checkICCMessage();}
function checkICCMessage(){var callMessageReq=navigator.mozSettings.createLock().get('icc.callmessage');callMessageReq.onsuccess=function onCallMessageSuccess(){self._iccCallMessage=callMessageReq.result['icc.callmessage'];if(self._iccCallMessage){if(typeof self._iccCallMessage==='string'){self.replacePhoneNumber(self._iccCallMessage,'end');self._cachedInfo=self._iccCallMessage;}else{if(self._iccCallMessage.blob){self.iccMessageBlobURL=URL.createObjectURL(self._iccCallMessage.blob);self.numberNode.style.backgroundImage='url('+self.iccMessageBlobURL+')';self.numberNode.style.backgroundRepeat='no-repeat';}
if(self._iccCallMessage.callMessage){self.replacePhoneNumber(self._iccCallMessage.callMessage,'end');self._cachedInfo=self._iccCallMessage.callMessage;}
if(self._iccCallMessage.blob&&!self._iccCallMessage.callMessage){self.numberNode.style.color='white';}}
navigator.mozSettings.createLock().set({'icc.callmessage':null});}};}
function lookupContact(contact,matchingTel,contactsWithSameNumber){if(self._iccCallMessage){return;}
var contactName=number;var contactNameExist=false;if(contact){if(contact.name&&contact.name.length&&contact.name[0]!==''){contactName=contact.name[0];contactNameExist=true;}else if(contact.org&&contact.org.length&&contact.org[0]!==''){contactName=contact.org[0];contactNameExist=true;}}
if(CallsHandler.setCNAPText(self.call,self.additionalTelNode,self.numberNode)&&(contact!==undefined)&&!contactNameExist){self.info=self.numberNode.textContent;CallsHandler.insertImsRecord(number,self.info);self._cachedInfo=self.numberNode.textContent;self.node.classList.add('additionalInfo');return;}
if(contact){self.info=contactName;var primaryInfo=Utils.getPhoneNumberPrimaryInfo(matchingTel,contact);var contactCopy={id:contact.id,name:contactName,org:contact.org,tel:contact.tel};if(primaryInfo){node.textContent=primaryInfo;self._cachedInfo=primaryInfo;}else{self._cachedInfo=self._('unknown');node.textContent=self._cachedInfo;}
self._cachedAdditionalTel=matchingTel.value;self._cachedAdditionalTelType=Utils.getPhoneNumberAdditionalInfo(matchingTel);self.replaceAdditionalContactInfo(self._cachedAdditionalTel,self._cachedAdditionalTelType);self.formatPhoneNumber('end');CallsHandler.insertImsRecord(number,self.info);if(CallScreen.memOnDevice()===256){return;}
var photo=ContactPhotoHelper.getFullResolution(contact);if(self.photo){CallScreen.updateCallsDisplay();}else if(photo){self.photo=photo;if(self.blobURL){URL.revokeObjectURL(self.blobURL);self.blobURL=null;}
PhotoResize.resize(photo).then(resizeBlob=>{self.blobURL=URL.createObjectURL(resizeBlob);self.photoItem.style.backgroundImage='url('+self.blobURL+')';self.photoItem.setAttribute('data-icon','');});var thumbnail=ContactPhotoHelper.getThumbnail(contact);contactCopy.photo=[thumbnail];CallScreen.updateCallsDisplay();}
return;}
self.info=number;self._cachedInfo=number;node.textContent=self._cachedInfo;CallsHandler.insertImsRecord(number,'');self._cachedAdditionalTel=self._('unknown');self._cachedAdditionalTelType='';self.replaceAdditionalContactInfo(self._cachedAdditionalTel,self._cachedAdditionalTelType);self.formatPhoneNumber('end');}};HandledCall.prototype.replaceAdditionalContactInfo=function hc_replaceAdditionalContactInfo(additionalTel,additionalTelType){if((!additionalTel&&!additionalTelType)||(additionalTel.trim()===''&&additionalTelType.trim()==='')){this.additionalTelNode.textContent='';this.additionalTelTypeNode.textContent='';this.node.classList.remove('additionalInfo');}else{if(additionalTel===this._('emergencyNumber')){this.additionalTelNode.textContent=additionalTel;}else{this.additionalTelNode.textContent=additionalTel.replace(/\s/g,'');}
this.additionalTelTypeNode.textContent=additionalTelType;this.node.classList.add('additionalInfo');}};HandledCall.prototype.formatPhoneNumber=function hc_formatPhoneNumber(ellipsisSide){if(this._removed){return;}
if(this.call.group){this.dialNumberNode.style='';return;}
var scenario=CallScreen.getScenario();if(scenario===FontSizeManager.CALL_WAITING&&this.call.state==='incoming'&&CallScreen.incomingContainer.classList.contains('displayed')){scenario=FontSizeManager.SECOND_INCOMING_CALL;}
FontSizeManager.adaptToSpace(scenario,this.dialNumberOuterNode,false,ellipsisSide);if(this.node.classList.contains('additionalInfo')){FontSizeManager.ensureFixedBaseline(scenario,this.dialNumberNode);}else{FontSizeManager.resetFixedBaseline(this.dialNumberNode);}};HandledCall.prototype.replacePhoneNumber=function hc_replacePhoneNumber(phoneNumber,ellipsisSide){this.numberNode.textContent=phoneNumber;if(phoneNumber.length){this.numberNode.parentNode.style.display="block";}
else{this.numberNode.parentNode.style.display="none";}
this.formatPhoneNumber(ellipsisSide);};HandledCall.prototype.updateDirection=function hc_updateDirection(){var classList=this.node.classList;if(this._initialState==='incoming'){classList.add('incoming');this.node.setAttribute('aria-label',this._('incoming'));}else{this.outgoing=true;classList.add('outgoing');if(!classList.contains('connected')){classList.add('connecting');}
this.node.setAttribute('aria-label',this._('outgoing'));}
if(this.call.state=='connected'){classList.add('ongoing');}
var call=this.call;var simNum=CallScreen.getSimNum(call);var statusIcon=this.node.querySelector('.status-icon');if(simNum===''){delete statusIcon.dataset.index;}else{statusIcon.dataset.index=simNum;}
if(CallsHandler.isVideoCall()){classList.add('video-call');}else{classList.remove('video-call');}};HandledCall.prototype.updateRttMode=function hc_updateRttMode(){this.node.classList.toggle('rtt-mode',this.call.rttMode==='full');if(this.call.rttMode==='full'&&this.call.state==='connected'&&!this.rttViewAdded){Rtt.addRttView(this.call,this._cachedInfo,this.durationChildNode);this.rttViewAdded=true;}
if(this.rttMode!==this.call.rttMode){this.rttMode=this.call.rttMode;if(!this.rttMode&&this.call.emergency){var dialogConfig={title:{id:'rtt',args:{}},body:{id:'rtt-emegency-downgrade'},accept:{name:'ok',l10nId:'ok',priority:2,callback:function(){}}};CallScreen.showConfirmDialog(dialogConfig);}}};HandledCall.prototype.remove=function hc_remove(){this._removed=true;this.call.removeEventListener('statechange',this);this.photo=null;if(CallScreen.supportVT()){const{videoCallProvider}=this.call;videoCallProvider.onsessionmodifyresponse=null;videoCallProvider.onsessionmodifyrequest=null;}
if(this.blobURL){URL.revokeObjectURL(this.blobURL);this.blobURL=null;}
if(this.iccMessageBlobURL){URL.revokeObjectURL(this.iccMessageBlobURL);this.iccMessageBlobURL=null;}
var currentDuration=ConferenceGroupHandler.isGroupDetailsShown()?ConferenceGroupHandler.currentDuration:this.durationNode.dataset.duration;var totalDuration=currentDuration?currentDuration:'';this.node.classList.add('ended');CallScreen.stopTicker(this.durationNode);if(document.body.classList.contains('single-line')){this.durationNode.classList.remove('isTimer');if(totalDuration===''){this.durationChildNode.textContent=this._('callEnded');}else{Utils.prettyDuration(this.durationChildNode,+currentDuration,'callEndedDuration');}}
var promptTime=CallsHandler.isAnyOpenCalls?CallScreen.callEndPromptTime:CallScreen.callNodeHideTime;if(CallsHandler.isInConferenceCall(this.call.id.number)){promptTime=0;}
setTimeout(()=>{CallScreen.removeCall(this.node);this.node=null;},promptTime);};HandledCall.prototype.connected=function hc_connected(){this.show();this.node.classList.remove('held');this.node.classList.remove('connecting');this.node.classList.add('connected');this.durationNode.classList.remove('isHeld');this.showStirIndicator(false);this.updateDirection();CallScreen.rendVoWifiQuality(this.durationNode.parentNode,true);CallScreen.createTicker(this.durationNode);const duration=this.durationNode.dataset.duration;if(duration&&document.body.classList.contains('single-line')){Utils.prettyDuration(this.durationChildNode,+duration);}
this.updateCallNumber();this._wasConnected=true;};HandledCall.prototype.held=function hc_held(){this.durationNode.classList.add('isHeld');const duration=this.durationNode.dataset.duration;if(duration&&document.body.classList.contains('single-line')){Utils.prettyDuration(this.durationChildNode,+duration,'callHeldDuration');}
CallScreen.rendVoWifiQuality(this.durationNode.parentNode,false);};HandledCall.prototype.disconnected=function hc_disconnected(){var self=this;if(this._leftGroup){CallScreen.showToast('call-left-conference-toast',self._cachedInfo.toString());self._leftGroup=false;}
if(this._wasConnected){TonePlayer.playSequence([[480,620,250]]);}
this._wasConnected=false;this.remove();this.showRecIndicator(false);this.showStirIndicator(false);if(this.rttViewAdded){Rtt.removeRttView(this.call);}};HandledCall.prototype.show=function hc_show(){if(this.node){this.node.hidden=false;}
CallScreen.updateCallsDisplay();};HandledCall.prototype.hide=function hc_hide(){if(this.node){this.node.hidden=true;}
CallScreen.updateCallsDisplay();};HandledCall.prototype.showRecIndicator=function hc_showRecIndicatorsss(display){CallScreen.showRecIndicator(this.node,display);};HandledCall.prototype.showStirIndicator=function hc_showStirIndicator(show){this.stirContainer.classList.toggle('hide',!show);this.stirChecked.classList.toggle('hide',!show);};HandledCall.prototype.getStartTime=function hc_getStartTime(){return this.durationNode.dataset.startTime;};