'use strict';let LockScreen=(function lockscreen(){const SCREEN_LOCK_STRING='lockscreen.locked';const PASSCODE_STRING='lockscreen.passcode-lock.code';const PASSCODE_INFO='lockscreen.wrong.code.info';const PASSCODE_SIZE=4;const coldDownMapping=[0,0,0,0,0,0,60,180,300,600,900];const COLD_DOWN_INTERVAL=1000;const VALIDING_TIMEOUT=300;const ERROR_STATE_TIMEOUT=1500;let screen=document.getElementById('lock-screen');let passcodeText=screen.querySelector('#passcode-text');let codes=screen.querySelectorAll('.code');let locked=false;let pause=false;let passcode='';let currentPasscode='';let errorTimes=0;let error=false;let retryTimestamp=null;let coldDown=false;let coldDownInterval=null;let _=navigator.mozL10n.get;function init(){SettingsListener.observe(SCREEN_LOCK_STRING,false,(value)=>{locked=value;});SettingsListener.observe(PASSCODE_STRING,'',(value)=>{passcode=value;});SettingsListener.observe(PASSCODE_INFO,null,(value)=>{if(value&&value.errorTimes){errorTimes=value.errorTimes;retryTimestamp=value.retryTimestamp;coldDown=!!getColdDownTime(errorTimes);error=coldDown||pause;updatePasscodeScreen();}else if(errorTimes){errorTimes=0;coldDown=false;error=false;}});}
function inputPasscodeScreen(){currentPasscode='';screen.classList.remove('error');passcodeText.textContent=_('enter-passcode');for(let i=0;i<codes.length;i++){codes[i].classList.remove('dotted');}}
function errorPasscodeScreen(message){currentPasscode='0000';screen.classList.add('error');passcodeText.textContent=message;for(let i=0;i<codes.length;i++){codes[i].classList.add('dotted');}}
function updatePasscodeScreen(){if(error){pause=false;const value=getInvalidCodeString();if(coldDown){if(!value.coldDown){coldDown=false;error=false;window.clearInterval(coldDownInterval);coldDownInterval=null;setTimeout(()=>{updatePasscodeScreen();},VALIDING_TIMEOUT);}else if(!coldDownInterval){coldDownInterval=setInterval(()=>{updatePasscodeScreen();},COLD_DOWN_INTERVAL);}}else{setTimeout(()=>{error=false;updatePasscodeScreen();},ERROR_STATE_TIMEOUT);}
errorPasscodeScreen(value.string);}else{inputPasscodeScreen();}}
function getColdDownTime(){const times=Math.min(coldDownMapping.length-1,errorTimes);return coldDownMapping[times];}
function getInvalidCodeString(){let leftColdDownTime=0;let string='';if(error){if(coldDown){const curTime=Date.now();if(curTime>=retryTimestamp){leftColdDownTime=Math.max(0,getColdDownTime()-
Math.floor((curTime-retryTimestamp)/1000));}
const timeString=new Date(2019,9,9,9,Math.floor(leftColdDownTime/60),leftColdDownTime%60).toLocaleString(navigator.language,{second:'numeric',minute:'numeric'});string=_('lockscreenColdDown',{n:timeString});}else{switch(errorTimes){case 3:case 4:case 5:string=_('lockscreenCheckLockCode',{n:6-errorTimes});break;default:string=_('lockscreenInvalidCode');break;}}}
return{string:string,coldDown:!!leftColdDownTime};}
function handleKeyDown(evt){let key=CallScreen.translateKey(evt.key);if(key>'9'||key<'0'||currentPasscode.length>=PASSCODE_SIZE){return;}
currentPasscode+=key;let length=currentPasscode.length;codes[length-1].classList.add('dotted');if(length===PASSCODE_SIZE){if(currentPasscode===passcode){handleValidationSuccess();}else{handleValidationError();}}}
function isScreenLocked(){return locked;}
function unlockScreen(){if(isScreenLocked){navigator.mozSettings.createLock().set({'lockscreen.unlocked':true});}}
function showLockScreen(show){if(show){updatePasscodeScreen();DtmfHelper.disableDtmf();screen.classList.add('display');CallScreenHelper.showLockScreenOption();window.addEventListener('keydown',handleKeyDown);}else{DtmfHelper.enableDtmf();screen.classList.remove('display');window.removeEventListener('keydown',handleKeyDown);}}
function isLockScreenShown(){return screen.classList.contains('display');}
function handleValidationSuccess(){setTimeout(()=>{showLockScreen(false);unlockScreen();CallScreen.placeNewCall();navigator.mozSettings.createLock().set({'lockscreen.wrong.code.info':{errorTimes:0}});},VALIDING_TIMEOUT);}
function handleValidationError(){pause=true;screen.classList.add('error');navigator.mozSettings.createLock().set({'lockscreen.wrong.code.info':{errorTimes:errorTimes+1,retryTimestamp:Date.now()}});}
return{init:init,isScreenLocked:isScreenLocked,showLockScreen:showLockScreen,isLockScreenShown:isLockScreenShown};})();