'use strict';const kMasterVolume=0.5;const kToneVolume=0.7;const kShortPressDuration=0.15;const kAttackDuration=0.025;const kDecayDuration=0.025;const kReleaseDuration=0.05;var TonePlayer={_audioContext:null,_channel:'telephony',_gainNode:null,_playingNodes:[],_maybeTrashAudio:null,_initialized:false,_envelopeNode:null,_audio:null,_notificationVolume:0,_notificationTone:null,_waitingTime:1000,init:function tp_init(){var telephony=navigator.mozTelephony;this._reset();this._maybeTrashAudio=(function tp_maybeTrashAudio(){var callIsActive=telephony&&(telephony.calls.length||telephony.conferenceGroup.calls.length||telephony.conferenceGroup.state);if(!callIsActive){setTimeout(()=>{if(!telephony.calls.length&&!telephony.conferenceGroup.calls.length){this._trashAudio();}},this._waitingTime);}}).bind(this);telephony&&telephony.addEventListener('callschanged',this._maybeTrashAudio);telephony&&telephony.conferenceGroup.addEventListener('statechange',this._maybeTrashAudio);SettingsListener.observe('audio.volume.notification',0,(value)=>{this._notificationVolume=value;});SettingsListener.observe('notification.ringtone',null,(value)=>{this._notificationTone=value;});this._initialized=true;},teardown:function tp_teardown(){var telephony=navigator.mozTelephony;telephony&&telephony.removeEventListener('callschanged',this._maybeTrashAudio);telephony&&telephony.conferenceGroup.removeEventListener('statechange',this._maybeTrashAudio);window.removeEventListener('visibilitychange',this._maybeTrashAudio);this._reset();this._initialized=false;},_reset:function tp_reset(){this._audioContext=null;this._gainNode=null;this._playingNodes=[];this._maybeTrashAudio=null;},_ensureAudio:function tp_ensureAudio(){if(this._audioContext||!this._initialized){return;}
this._audioContext=new AudioContext(this._channel);},_trashAudio:function tp_trashAudio(){this.stop();if(this._envelopeNode){this._envelopeNode.disconnect();}
if(this._audioContext){this._audioContext.close();}
this._envelopeNode=null;this._audioContext=null;},_startAt:function tp_startAt(frequencies,when,duration){this._audioContext.forceAudioChannelPlaying(true);var context=this._audioContext;var sampleRate=context.sampleRate;var envelope=context.createBuffer(1,(duration?duration:0.05)*sampleRate,sampleRate);for(var i=0;i<envelope.length;i++){var factor=kToneVolume;var t=i/sampleRate;if(t<=kAttackDuration){factor=t/kAttackDuration;}else if(t-kAttackDuration<=kDecayDuration){factor=1.0-(1.0-kToneVolume)*(t-kAttackDuration)/kDecayDuration;}
if(!duration){factor-=kToneVolume;}else if(t>duration-kReleaseDuration){factor*=(duration-t)/kReleaseDuration;}
envelope.getChannelData(0)[i]=factor*kMasterVolume;}
var gainNode=context.createGain();gainNode.connect(context.destination);if(!duration){this._gainNode=gainNode;}
var envelopeNode=context.createBufferSource();envelopeNode.buffer=envelope;envelopeNode.start(when);envelopeNode.connect(gainNode.gain);this._envelopeNode=envelopeNode;gainNode.gain.setValueAtTime(duration?0.0:kToneVolume*kMasterVolume,0.0);for(i=0;i<frequencies.length;++i){var oscNode=this._audioContext.createOscillator();oscNode.type='sine';oscNode.frequency.value=frequencies[i];oscNode.start(when);if(duration){oscNode.stop(Math.max(when,context.currentTime+0.5)+duration);}else{this._playingNodes.push(oscNode);}
oscNode.connect(gainNode);}},start:function tp_start(frequencies,shortPress){this._ensureAudio();this._startAt(frequencies,0,shortPress?kShortPressDuration:0);},stop:function tp_stop(){if(!this._gainNode){return;}
var context=this._audioContext;var sampleRate=context.sampleRate;var gain=this._gainNode.gain;this._gainNode=null;var ramp=context.createBuffer(1,kReleaseDuration*sampleRate,sampleRate);for(var i=0;i<ramp.length;i++){ramp.getChannelData(0)[i]=(ramp.length-i-1)/ramp.length*kToneVolume*kMasterVolume;}
var rampNode=context.createBufferSource();rampNode.buffer=ramp;rampNode.start();rampNode.connect(gain);gain.setValueAtTime(0.0,0.0);while(this._playingNodes.length){this._playingNodes.pop().stop(context.currentTime+kReleaseDuration+0.5);}},playSequence:function tp_playSequence(sequence){this._ensureAudio();var when=this._audioContext.currentTime+0.2;for(var index=0;index<sequence.length;++index){var step=sequence[index];var frequencies=step.slice(0,2);var duration=step[2]/1000;this._startAt(frequencies,when,duration);when+=duration;}},stopRingtone:function tp_stopRingtone(){if(this._audio&&!this._audio.paused){this._audio.pause();}},playRingtone:function tp_playRingtone(soundFile){this.stopRingtone();if(!this._audio){this._audio=new Audio();}
var settingsUrl=new SettingsURL();this._audio.src=settingsUrl.set(soundFile);this._audio.mozAudioChannelType=this._channel;this._audio.play();window.setTimeout(()=>{this._audio.pause();this._audio.removeAttribute('src');this._audio.load();},2000);},playNotice:function tp_playNotice(){if(this._notificationVolume&&this._notificationTone){this.playRingtone(this._notificationTone);}else{navigator.vibrate([200]);}},setWaitingTime:function tp_setWaitingTime(time){this._waitingTime=time+300;window.setTimeout(()=>{this._waitingTime=1000;},this._waitingTime);}};