'use strict';(function(exports){var VT=function(){this.telephony=navigator.mozTelephony;this.localPrepared=false;this.remotePrepared=false;this.remoteSurface=null;this.setCameraOn(false);this.setCameraFront(true);this.callOldState='Voice';this.callConnectingState='';this.userRequestVoice=false;this.frontSensorAngle=0;this.rearSensorAngle=0;this.frontLandscape=false;this.rearLandscape=false;this.start();this.handleConfirmDlgEvents=this._handleConfirmDlgEvents.bind(this);this.EVENTS.forEach((name)=>{this['handle_'+name]=this['_handle_'+name].bind(this);});this.handleConfirmDlgEvents=this._handleConfirmDlgEvents.bind(this);};VT.prototype.DEBUG=true;VT.prototype._debug=function(info){if(this.DEBUG){console.log(info);}};VT.prototype.EVENTS=['alerting','connected','dialing','disconnected','statechange'];VT.prototype.start=function(){navigator.hasFeature&&navigator.hasFeature('device.capability.vilte').then((hasVT)=>{if(hasVT){this.telephony.addEventListener('callschanged',this._onCallsChanged.bind(this));this._getSensorAngle();}});};VT.prototype._getSensorAngle=function(){navigator.mozCameras.getCameraSensorAngle('back').then((sensorAngle)=>{this.rearSensorAngle=sensorAngle;if((sensorAngle%180!==0&&screen.orientation.type.indexOf('portrait')!==-1)||(sensorAngle%180===0&&screen.orientation.type.indexOf('portrait')===-1)){this.rearLandscape=true;}});navigator.mozCameras.getCameraSensorAngle('front').then((sensorAngle)=>{this.frontSensorAngle=sensorAngle;if((sensorAngle%180!==0&&screen.orientation.type.indexOf('portrait')!==-1)||(sensorAngle%180===0&&screen.orientation.type.indexOf('portrait')===-1)){this.frontLandscape=true;}});};VT.prototype._setLocalVideoViewRotation=function(camera){var handledCallNode=document.getElementById('list-call');var localVideoView=handledCallNode.querySelector('.local-video-view');var transform='';var sensorAngle;var landscape;if(camera==='front'){transform='scale(-1, 1) ';sensorAngle=this.frontSensorAngle;landscape=this.frontLandscape;}else{sensorAngle=this.rearSensorAngle;landscape=this.rearLandscape;}
sensorAngle%180?localVideoView.classList.add('rotate'):localVideoView.classList.remove('rotate');landscape?localVideoView.classList.add('landscape'):localVideoView.classList.remove('landscape');localVideoView.style.transform=transform+'rotate('+sensorAngle+'deg)';};VT.prototype._getElements=function(option){var node;if(CallsHandler.activeCall){node=CallsHandler.activeCall.node;}else if(CallsHandler.incomingCall){node=CallsHandler.incomingCall.node;}else{this._debug('VT_call _getElements return null');return;}
if(option==='local'){this.localAnchor=node.getElementsByClassName('local-video-anchor')[0];this.localView=node.getElementsByClassName('local-video-view')[0];}else if(option==='remote'){this.remoteAnchor=node.getElementsByClassName('remote-video-anchor')[0];this.remoteView=node.getElementsByClassName('remote-video-view')[0];}};VT.prototype._isBidirectional=function(call){return call.videoCallState==='Bidirectional';};VT.prototype._onCallsChanged=function(){if(this.telephony.conferenceGroup.calls.length||this.telephony.calls.length!==1){return;}
var call=this.telephony.calls[0];if(!call){return;}
this._debug('VT_call oncallschanged state is: '+call.videoCallState);this.EVENTS.forEach((name)=>{call.addEventListener(name,this['handle_'+name]);});if((call.state==='dialing'||call.state==='alerting')&&CallsHandler.isVideoCall()){this._showLocalAnchor(true);CallsHandler.enableSpeakerForVT();}};VT.prototype._handle_alerting=function(event){var call=event.target;this._debug('VT_call alerting state is: '+call.videoCallState+', this.localPrepared='+this.localPrepared);this.callConnectingState=call.videoCallState;};VT.prototype._handle_dialing=function(event){var call=event.target;this._debug('VT_call dialing state is: '+call.videoCallState);this.callConnectingState=call.videoCallState;};VT.prototype._handle_connected=function(event){var call=event.target;if('Bidirectional'===this.callConnectingState&&'Voice'===call.videoCallState){var msgId=!CallsHandler.isSupportedVT()?'video-call-not-support':'video-call-rejected';CallScreen.showToast(msgId);}
this.callConnectingState='';CallsHandler.handleCallInfoTimer(true);};VT.prototype._handle_disconnected=function(event){this.releaseCamera(event.target);this._showLocalAnchor(false);this._hideStreams('remote');CallsHandler.isShowInfo=true;this.setCameraFront(true);this.callOldState='Voice';this.callConnectingState='';this.userRequestVoice=false;this.remoteSurface=null;CallScreen.closeConfirmDialog();var call=event.target;this.EVENTS.forEach((name)=>{call.removeEventListener(name,this['handle_'+name]);});};VT.prototype._handle_statechange=function(event){if(this.telephony.conferenceGroup.calls.length||this.telephony.calls.length!==1){return;}
var call=event.target;if(!call||'connected'!==call.state||(call.videoCallState===this.callOldState　&&!this.isCameraOn())){return;}
this.callOldState=call.videoCallState;this._debug('VT_call _handle_statechange call.videoCallState='+
call.videoCallState);var handledCallNode=document.getElementById('list-call');if('Bidirectional'===call.videoCallState){handledCallNode.querySelector('.local-video-view').classList.remove('full');this._showLocalAnchor(true);this._showRemoteAnchor(true);}else if('RxEnabled'===call.videoCallState){this.releaseCamera(call);this._showLocalAnchor(false);this._showRemoteAnchor(true);}else if('TxEnabled'===call.videoCallState){handledCallNode.querySelector('.local-video-view').classList.remove('full');this._showLocalAnchor(true);this._showRemoteAnchor(false);}else if('Voice'===call.videoCallState){if(this.userRequestVoice){this.userRequestVoice=false;}else{CallScreen.showToast('call-downgraded');}
if(this.isCameraOn()){this.releaseCamera(call);handledCallNode.querySelector('.local-video-view').classList.remove('full');CallScreenHelper.render();}
this._showLocalAnchor(false);this._showRemoteAnchor(false);}
if(!CallsHandler.isShowInfo){CallsHandler.toggleShowInfo();}};VT.prototype.releaseCamera=function(call){if(!call){return;}
if(this.isCameraOn()){var videoCallProvider=call.videoCallProvider;videoCallProvider.setCamera();this.setCameraOn(false);}};VT.prototype.onsessionmodifyresponse=function(call,resp){if(!call||!resp){return;}
this._debug('VT_call call resp.status='+resp.status);if('timed-out'===resp.status){CallScreen.closeConfirmDialog();}else if('rejected-by-remote'===resp.status||'fail'===resp.status){if(CallsHandler.isVideoCall()){return;}
if('rejected-by-remote'===resp.status){CallScreen.showToast('video-call-rejected-timeout');}
var handledCallNode=document.getElementById('list-call');handledCallNode.querySelector('.local-video-view').classList.remove('full');this.releaseCamera(call);this._showLocalAnchor(false);this._hideStreams('remote');CallScreenHelper.render();}else if('success'===resp.status){CallsHandler.enableSpeakerForVT();}};VT.prototype.onsessionmodifyrequest=function(call,req){if(!call||!req){return;}
if(req.request.state==='audio-only'){return;}
var videoCallProvider=call.videoCallProvider;if(this.telephony.conferenceGroup.calls.length||this.telephony.calls.length!==1){req.request.state=this._getCallType(call.videoCallState);req.request.quality='default';videoCallProvider.sendSessionModifyResponse(req.request);return;}
var header='videoCall';var message='video-call-from';var tempName=call.id.number;window.addEventListener('gaia-confirm-open',this.handleConfirmDlgEvents);Contacts.findByNumber(call.id.number,function(contact,matchingTel){if(contact&&matchingTel){var primaryInfo=Utils.getPhoneNumberPrimaryInfo(matchingTel,contact);tempName=primaryInfo[0];}
var dialogConfig={title:{id:header,args:{}},body:{id:message,args:{name:tempName}},cancel:{name:'Cancel',l10nId:'cancel',priority:1,callback:()=>{req.request.state=this._getCallType(call.videoCallState);req.request.quality='default';videoCallProvider.sendSessionModifyResponse(req.request);}},confirm:{name:'Accept',l10nId:'accept',priority:3,callback:()=>{this._prepareLocalStreams('front').then((surface)=>{this.localView.mozSrcObject=surface;this.localAnchor.hidden=true;});this._prepareRemoteStreams().then((surface)=>{this.remoteView.mozSrcObject=surface;this.remoteAnchor.hidden=true;});videoCallProvider.sendSessionModifyResponse(req.request);CallsHandler.enableSpeakerForVT();}}};CallScreen.showConfirmDialog(dialogConfig);}.bind(this));TonePlayer.playNotice();};VT.prototype._getCallType=function(videoCallState){var callType=null;switch(videoCallState){case'Bidirectional':callType='bidirectional';break;case'TxEnabled':callType='tx-enabled';break;case'RxEnabled':callType='rx-enabled';break;case'Voice':callType='audio-only';break;default:break;}
return callType;};VT.prototype._showLocalAnchor=function(isShow){if(isShow){if(this.localPrepared){this._showStreams('local');}else{var type=this.isCameraFront()?'front':'rear';this._prepareLocalStreams(type).then((surface)=>{this.localView.mozSrcObject=surface;this.localAnchor.hidden=true;this._showStreams('local');});}}else{this._hideStreams('local');this.localAnchor.hidden=true;}};VT.prototype._showRemoteAnchor=function(isShow){if(isShow){if(this.remotePrepared){this._showStreams('remote');}else{this._prepareRemoteStreams().then((surface)=>{this.remoteView.mozSrcObject=surface;this.remoteAnchor.hidden=true;this._showStreams('remote');});}}else{this._hideStreams('remote');}};VT.prototype._prepareLocalStreams=function(camera){return new Promise((resolve,reject)=>{if(this.localPrepared){this._debug('VT_call localPrepared');reject();return;}
this.localPrepared=true;var videoCallProvider=this.telephony.calls[0].videoCallProvider;var localOptions={previewSize:{width:320,height:240}};var handledCallNode=document.getElementById('list-call');if('front'===camera){videoCallProvider.setCamera('front');this._setLocalVideoViewRotation('front');this.setCameraFront(true);}else{videoCallProvider.setCamera('rear');this._setLocalVideoViewRotation('rear');this.setCameraFront(false);}
this.setCameraOn(true);this._getElements('local');videoCallProvider.getPreviewStream(localOptions).then((surface)=>{this._debug('VT_call local got surface');resolve(surface);});});};VT.prototype._prepareRemoteStreams=function(){return new Promise((resolve,reject)=>{if(this.remotePrepared){this._debug('VT call remotePrepared');reject();return;}
if(this.remoteSurface){resolve(this.remoteSurface);return;}
this.remotePrepared=true;var videoCallProvider=this.telephony.calls[0].videoCallProvider;var remoteOptions={previewSize:{width:240,height:320}};this._getElements('remote');videoCallProvider.onchangepeerdimensions=(evt)=>{this._debug('VT_call remoteWidth:'+evt.width+',remoteHeight'+evt.height);if(evt.width>evt.height){this.remoteView.classList.add('landscapeView');}else{this.remoteView.classList.remove('landscapeView');}};videoCallProvider.getDisplayStream(remoteOptions).then((surface)=>{this._debug('VT_call remote got surface');this.remoteSurface=surface;resolve(surface);});});};VT.prototype._showStreams=function(option){this._debug('VT_call _showStreams option = '+option);if(option==='local'){if(!this.localAnchor||!this.localAnchor.hidden){return;}
if(!this.isCameraOn()){return;}
var handledCallNode=document.getElementById('list-call');handledCallNode.querySelector('.local-video-anchor').classList.remove('hide-camera');var callState=this.telephony.calls[0].state;if('alerting'===callState||'dialing'===callState){handledCallNode.querySelector('.local-video-view').classList.add('full');}
this.localAnchor.hidden=false;if(this.localView){this.localView.play();}}else if(option==='remote'){if(!this.remoteAnchor||!this.remoteAnchor.hidden){return;}
this.remoteAnchor.hidden=false;if(this.remoteView){this.remoteView.play();}}};VT.prototype._hideStreams=function(option){if(option==='local'){if(!this.localAnchor){return;}
if(!this.isCameraOn()){var handledCallNode=document.getElementById('list-call');handledCallNode.querySelector('.local-video-anchor').classList.add('hide-camera');}
if(this.localView){this.localView.pause();if(this.localView.mozSrcObject){this.localView.mozSrcObject=null;}}
this.localPrepared=false;}else if(option==='remote'){if(!this.remoteAnchor){return;}
if(this.remoteView){this.remoteView.pause();if(this.remoteView.mozSrcObject){this.remoteView.mozSrcObject=null;}}
this.remoteAnchor.hidden=true;this.remotePrepared=false;}};VT.prototype.isCameraOn=function(){this._debug('VT_call isCameraOn='+this.CameraOn);return this.CameraOn;};VT.prototype.setCameraOn=function(status){this._debug('VT_call setCameraOn='+status);this.CameraOn=status;};VT.prototype.isCameraFront=function(){this._debug('VT_call isCameraFront='+this.cameraFront);return this.cameraFront;};VT.prototype.setCameraFront=function(status){this._debug('VT_call setCameraFront='+status);this.cameraFront=status;};VT.prototype._handleConfirmDlgEvents=function(evt){switch(evt.type){case'gaia-confirm-close':window.removeEventListener('gaia-confirm-close',this.handleConfirmDlgEvents);CallScreen.unlockScreenWake();break;case'gaia-confirm-open':window.removeEventListener('gaia-confirm-open',this.handleConfirmDlgEvents);window.addEventListener('gaia-confirm-close',this.handleConfirmDlgEvents);CallScreen.lockScreenWake();break;default:return;}};VT.prototype.requestVoice=function(){this.userRequestVoice=true;};exports.VT=new VT();})(window);